<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DapurRiwayatBarangTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('dapur_riwayat_barang')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('dapur_riwayat_barang')->insert(array (
          0 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 27.0,
            'masuk' => 1.0,
            'keluar' => 0.0,
            'stok_akhir' => 28.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '15:43:50',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          1 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 382.0,
            'masuk' => 1.0,
            'keluar' => 0.0,
            'stok_akhir' => 383.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '15:43:50',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          2 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 28.0,
            'masuk' => 0.0,
            'keluar' => 1.0,
            'stok_akhir' => 27.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '19:38:53',
            'petugas' => 'Admin Utama',
            'status' => 'Hapus',
          ),
          3 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 383.0,
            'masuk' => 0.0,
            'keluar' => 1.0,
            'stok_akhir' => 382.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '19:38:53',
            'petugas' => 'Admin Utama',
            'status' => 'Hapus',
          ),
          4 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 27.0,
            'masuk' => 2.0,
            'keluar' => 0.0,
            'stok_akhir' => 29.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '19:39:49',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          5 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 382.0,
            'masuk' => 1.0,
            'keluar' => 0.0,
            'stok_akhir' => 383.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-14',
            'jam' => '19:39:49',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          6 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 29.0,
            'masuk' => 3.0,
            'keluar' => 0.0,
            'stok_akhir' => 32.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-15',
            'jam' => '21:18:58',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          7 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 383.0,
            'masuk' => 2.0,
            'keluar' => 0.0,
            'stok_akhir' => 385.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-15',
            'jam' => '21:18:58',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          8 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 32.0,
            'masuk' => 3.0,
            'keluar' => 0.0,
            'stok_akhir' => 35.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-15',
            'jam' => '21:19:06',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          9 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 385.0,
            'masuk' => 2.0,
            'keluar' => 0.0,
            'stok_akhir' => 387.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-15',
            'jam' => '21:19:06',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          10 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 35.0,
            'masuk' => 0.0,
            'keluar' => 3.0,
            'stok_akhir' => 32.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-17',
            'jam' => '21:27:19',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          11 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 387.0,
            'masuk' => 0.0,
            'keluar' => 1.0,
            'stok_akhir' => 386.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-17',
            'jam' => '21:27:19',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          12 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 32.0,
            'masuk' => 3.0,
            'keluar' => 0.0,
            'stok_akhir' => 35.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-17',
            'jam' => '22:25:37',
            'petugas' => 'Admin Utama',
            'status' => 'Hapus',
          ),
          13 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 386.0,
            'masuk' => 1.0,
            'keluar' => 0.0,
            'stok_akhir' => 387.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-17',
            'jam' => '22:25:37',
            'petugas' => 'Admin Utama',
            'status' => 'Hapus',
          ),
          14 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 35.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 45.0,
            'posisi' => 'Hibah',
            'tanggal' => '2024-11-18',
            'jam' => '09:32:30',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          15 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 387.0,
            'masuk' => 2.0,
            'keluar' => 0.0,
            'stok_akhir' => 389.0,
            'posisi' => 'Hibah',
            'tanggal' => '2024-11-18',
            'jam' => '09:32:30',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          16 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 45.0,
            'masuk' => 0.0,
            'keluar' => 10.0,
            'stok_akhir' => 35.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-18',
            'jam' => '20:12:26',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          17 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 389.0,
            'masuk' => 0.0,
            'keluar' => 4.0,
            'stok_akhir' => 385.0,
            'posisi' => 'Retur Beli',
            'tanggal' => '2024-11-18',
            'jam' => '20:12:26',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          18 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 35.0,
            'masuk' => 0.0,
            'keluar' => 10.0,
            'stok_akhir' => 25.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2024-11-19',
            'jam' => '12:10:59',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          19 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 385.0,
            'masuk' => 0.0,
            'keluar' => 3.0,
            'stok_akhir' => 382.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2024-11-19',
            'jam' => '12:10:59',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          20 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 25.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 35.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-20',
            'jam' => '10:01:32',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          21 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 382.0,
            'masuk' => 3.0,
            'keluar' => 0.0,
            'stok_akhir' => 385.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-20',
            'jam' => '10:01:32',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          22 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 0.0,
            'masuk' => 200.0,
            'keluar' => 0.0,
            'stok_akhir' => 200.0,
            'posisi' => 'Opname',
            'tanggal' => '2024-11-22',
            'jam' => '05:33:32',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          23 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 200.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 300.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:37:33',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          24 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 35.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 135.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:37:33',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          25 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 385.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 485.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:37:33',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          26 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 300.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 400.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:41:03',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          27 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 135.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 235.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:41:03',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          28 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 485.0,
            'masuk' => 90.0,
            'keluar' => 0.0,
            'stok_akhir' => 575.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-22',
            'jam' => '05:41:03',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          29 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 400.0,
            'masuk' => 0.0,
            'keluar' => 5.0,
            'stok_akhir' => 395.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2024-11-22',
            'jam' => '05:42:43',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          30 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 235.0,
            'masuk' => 0.0,
            'keluar' => 5.0,
            'stok_akhir' => 230.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2024-11-22',
            'jam' => '05:42:43',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          31 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 575.0,
            'masuk' => 0.0,
            'keluar' => 5.0,
            'stok_akhir' => 570.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2024-11-22',
            'jam' => '05:42:43',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          32 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 395.0,
            'masuk' => 90.0,
            'keluar' => 0.0,
            'stok_akhir' => 485.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-26',
            'jam' => '14:36:26',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          33 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 230.0,
            'masuk' => 46.0,
            'keluar' => 0.0,
            'stok_akhir' => 276.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-26',
            'jam' => '14:36:26',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          34 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 570.0,
            'masuk' => 100.0,
            'keluar' => 0.0,
            'stok_akhir' => 670.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2024-11-26',
            'jam' => '14:36:26',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          35 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 485.0,
            'masuk' => 8.0,
            'keluar' => 0.0,
            'stok_akhir' => 493.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-02-11',
            'jam' => '15:15:34',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          36 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 276.0,
            'masuk' => 8.0,
            'keluar' => 0.0,
            'stok_akhir' => 284.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-02-11',
            'jam' => '15:15:34',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          37 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 670.0,
            'masuk' => 7.0,
            'keluar' => 0.0,
            'stok_akhir' => 677.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-02-11',
            'jam' => '15:15:34',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          38 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 493.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 503.0,
            'posisi' => 'Pengadaan',
            'tanggal' => '2025-04-28',
            'jam' => '09:57:11',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          39 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 284.0,
            'masuk' => 20.0,
            'keluar' => 0.0,
            'stok_akhir' => 304.0,
            'posisi' => 'Pengadaan',
            'tanggal' => '2025-04-28',
            'jam' => '09:57:11',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          40 => 
          array (
            'kode_brng' => 'D00004',
            'stok_awal' => 0.0,
            'masuk' => 5.5,
            'keluar' => 0.0,
            'stok_akhir' => 5.5,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-07-08',
            'jam' => '10:57:01',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          41 => 
          array (
            'kode_brng' => 'D00004',
            'stok_awal' => 5.5,
            'masuk' => 0.0,
            'keluar' => 1.5,
            'stok_akhir' => 4.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-07-08',
            'jam' => '10:57:35',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          42 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 503.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 513.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-08-04',
            'jam' => '15:02:06',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          43 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 304.0,
            'masuk' => 8.0,
            'keluar' => 0.0,
            'stok_akhir' => 312.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-08-04',
            'jam' => '15:02:06',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          44 => 
          array (
            'kode_brng' => 'D00004',
            'stok_awal' => 4.0,
            'masuk' => 50.0,
            'keluar' => 0.0,
            'stok_akhir' => 54.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-08-04',
            'jam' => '15:03:10',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          45 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 312.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 322.0,
            'posisi' => 'Penerimaan',
            'tanggal' => '2025-08-04',
            'jam' => '15:03:10',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          46 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 513.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 523.0,
            'posisi' => 'Pengadaan',
            'tanggal' => '2025-08-04',
            'jam' => '15:06:54',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          47 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 677.0,
            'masuk' => 0.0,
            'keluar' => 3.0,
            'stok_akhir' => 674.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-08-04',
            'jam' => '15:08:38',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          48 => 
          array (
            'kode_brng' => 'D00002',
            'stok_awal' => 322.0,
            'masuk' => 0.0,
            'keluar' => 1.0,
            'stok_akhir' => 321.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-08-04',
            'jam' => '15:09:17',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          49 => 
          array (
            'kode_brng' => 'D00001',
            'stok_awal' => 674.0,
            'masuk' => 0.0,
            'keluar' => 50.0,
            'stok_akhir' => 624.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-08-04',
            'jam' => '15:09:17',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          50 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 523.0,
            'masuk' => 10.0,
            'keluar' => 0.0,
            'stok_akhir' => 533.0,
            'posisi' => 'Pengadaan',
            'tanggal' => '2025-08-19',
            'jam' => '14:12:41',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          51 => 
          array (
            'kode_brng' => 'D00004',
            'stok_awal' => 54.0,
            'masuk' => 2.0,
            'keluar' => 0.0,
            'stok_akhir' => 56.0,
            'posisi' => 'Pengadaan',
            'tanggal' => '2025-08-19',
            'jam' => '14:12:41',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          52 => 
          array (
            'kode_brng' => 'D00003',
            'stok_awal' => 533.0,
            'masuk' => 0.0,
            'keluar' => 4.0,
            'stok_akhir' => 529.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-08-19',
            'jam' => '14:13:05',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
          53 => 
          array (
            'kode_brng' => 'D00004',
            'stok_awal' => 56.0,
            'masuk' => 0.0,
            'keluar' => 1.0,
            'stok_akhir' => 55.0,
            'posisi' => 'Stok Keluar',
            'tanggal' => '2025-08-19',
            'jam' => '14:13:05',
            'petugas' => 'Admin Utama',
            'status' => 'Simpan',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}