<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DataBatchTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('data_batch')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('data_batch')->insert(array (
          0 => 
          array (
            'no_batch' => '123123',
            'kode_brng' => 'B000000560',
            'tgl_beli' => '2024-12-10',
            'tgl_kadaluarsa' => '2025-05-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB20241210003',
            'dasar' => 9751.0,
            'h_beli' => 9751.0,
            'ralan' => 11702.0,
            'kelas1' => 11702.0,
            'kelas2' => 11702.0,
            'kelas3' => 11702.0,
            'utama' => 11702.0,
            'vip' => 11702.0,
            'vvip' => 11702.0,
            'beliluar' => 11702.0,
            'jualbebas' => 11702.0,
            'karyawan' => 11702.0,
            'jumlahbeli' => 100.0,
            'sisa' => 100.0,
          ),
          1 => 
          array (
            'no_batch' => '54321',
            'kode_brng' => 'B000001659',
            'tgl_beli' => '2024-12-10',
            'tgl_kadaluarsa' => '2026-02-19',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB20241210003',
            'dasar' => 539.0,
            'h_beli' => 539.0,
            'ralan' => 647.0,
            'kelas1' => 647.0,
            'kelas2' => 647.0,
            'kelas3' => 647.0,
            'utama' => 647.0,
            'vip' => 647.0,
            'vvip' => 647.0,
            'beliluar' => 647.0,
            'jualbebas' => 647.0,
            'karyawan' => 647.0,
            'jumlahbeli' => 100.0,
            'sisa' => 100.0,
          ),
          2 => 
          array (
            'no_batch' => 'BATCH-TEST-001',
            'kode_brng' => '2018001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2026-12-02',
            'asal' => 'Penerimaan',
            'no_faktur' => 'TEST-FAKTUR-2025-12-',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 5.0,
          ),
          3 => 
          array (
            'no_batch' => 'BATCH001',
            'kode_brng' => '2018001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2027-12-02',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251202-001',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 1.0,
          ),
          4 => 
          array (
            'no_batch' => 'BATCH001',
            'kode_brng' => '2018001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2027-12-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251203-001',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 1.0,
          ),
          5 => 
          array (
            'no_batch' => 'BATCH001',
            'kode_brng' => 'B000000571',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-002',
            'dasar' => 0.0,
            'h_beli' => 3330.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 100.0,
          ),
          6 => 
          array (
            'no_batch' => 'BATCH001',
            'kode_brng' => 'B000000965',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-002',
            'dasar' => 0.0,
            'h_beli' => 333.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 100.0,
          ),
          7 => 
          array (
            'no_batch' => 'BATCH001',
            'kode_brng' => 'B000001170',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-002',
            'dasar' => 0.0,
            'h_beli' => 162.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 100.0,
          ),
          8 => 
          array (
            'no_batch' => 'BATCHT1',
            'kode_brng' => 'A000000001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-04',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-T1',
            'dasar' => 0.0,
            'h_beli' => 15000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 10.0,
          ),
          9 => 
          array (
            'no_batch' => 'BATCHT2',
            'kode_brng' => 'A000000001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-04',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-T2',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 10.0,
          ),
          10 => 
          array (
            'no_batch' => 'BATCHT3',
            'kode_brng' => 'A000000001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-04',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-T3',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 10.0,
          ),
          11 => 
          array (
            'no_batch' => 'BATCHT4',
            'kode_brng' => 'A000000001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-04',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-T4',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 10.0,
          ),
          12 => 
          array (
            'no_batch' => 'BATCHTEST',
            'kode_brng' => '2018001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2028-12-04',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-003',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 1.0,
          ),
          13 => 
          array (
            'no_batch' => 'BATCHTEST-001',
            'kode_brng' => 'B000001294',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2026-12-31',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251204-001',
            'dasar' => 0.0,
            'h_beli' => 2750.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 5.0,
          ),
          14 => 
          array (
            'no_batch' => 'TESTBATCH001',
            'kode_brng' => '2018001',
            'tgl_beli' => '0000-00-00',
            'tgl_kadaluarsa' => '2026-12-03',
            'asal' => 'Penerimaan',
            'no_faktur' => 'PB-20251203-002',
            'dasar' => 0.0,
            'h_beli' => 20000.0,
            'ralan' => NULL,
            'kelas1' => NULL,
            'kelas2' => NULL,
            'kelas3' => NULL,
            'utama' => NULL,
            'vip' => NULL,
            'vvip' => NULL,
            'beliluar' => NULL,
            'jualbebas' => NULL,
            'karyawan' => NULL,
            'jumlahbeli' => 0.0,
            'sisa' => 5.0,
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}