<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class K3rsPeristiwaTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('k3rs_peristiwa')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('k3rs_peristiwa')->insert(array (
          0 => 
          array (
            'no_k3rs' => 'K3/2021/11/27/0001',
            'tgl_insiden' => '2021-11-27',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK002',
            'tgl_pelaporan' => '2021-11-27',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'ADA KECOAK LEWAT, KAGET, SUNTIKAN JATUH DAN TERINJAK',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000002',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'TIDAK WASPADA',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '12/09/1988/001',
            'perbaikan_jenis_tindakan' => 'Tindakan Pencegahan',
            'perbaikan_rencana_tindakan' => 'PEST KONTROL',
            'perbaikan_target' => '2021-11-27',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => '12/09/1988/001',
            'catatan' => '-',
          ),
          1 => 
          array (
            'no_k3rs' => 'K3/2022/06/09/0001',
            'tgl_insiden' => '2022-06-09',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2022-06-09',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'melamun, habis beratem dengan suami. melamun, jatuh, tertusuk jarum da tertimpa rak',
            'kode_penyebab' => 'PK006',
            'nik' => 'D0000003',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK001',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'melamun',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => 'keluarega',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => 'D0000004',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'koseling',
            'perbaikan_target' => '2022-06-09',
            'perbaikan_wewenang' => '-',
            'nik_timk3' => '08998998',
            'catatan' => '-',
          ),
          2 => 
          array (
            'no_k3rs' => 'K3/2022/06/18/0001',
            'tgl_insiden' => '2022-06-18',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2022-06-18',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'kecoak lewat, kaget, jarum jatuh, terinjak, tembus kaki',
            'kode_penyebab' => 'PK004',
            'nik' => '010101',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 3,
            'penyebab_langsung_kondisi' => 'lingkungan kotor',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => 'D0000003',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'pest control',
            'perbaikan_target' => '2022-06-18',
            'perbaikan_wewenang' => 'kesling',
            'nik_timk3' => 'D0000004',
            'catatan' => '-',
          ),
          3 => 
          array (
            'no_k3rs' => 'K3/2022/06/21/0001',
            'tgl_insiden' => '2022-06-21',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2022-06-21',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'baru nginfus, kecoak lewat, kaget, jatuh, jarum tertusuk kaki',
            'kode_penyebab' => 'PK004',
            'nik' => '08998998',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK002',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'lingkungann kotor, banyak kecoa',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => 'D0000004',
            'perbaikan_jenis_tindakan' => 'Tindakan Pencegahan',
            'perbaikan_rencana_tindakan' => 'pest kontrol',
            'perbaikan_target' => '2022-06-21',
            'perbaikan_wewenang' => 'kesling',
            'nik_timk3' => 'D0000003',
            'catatan' => '-',
          ),
          4 => 
          array (
            'no_k3rs' => 'K3/2022/08/03/0001',
            'tgl_insiden' => '2022-08-03',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2022-08-03',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'mau nyuntik pasien, kecoak lewat, kaget, jarum jatuh, terinjak kaki',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000004',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 3,
            'penyebab_langsung_kondisi' => '-',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '010101',
            'perbaikan_jenis_tindakan' => 'Tindakan Pencegahan',
            'perbaikan_rencana_tindakan' => 'pest kontrol',
            'perbaikan_target' => '2022-08-03',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => '08998998',
            'catatan' => '-',
          ),
          5 => 
          array (
            'no_k3rs' => 'K3/2022/08/05/0001',
            'tgl_insiden' => '2022-08-05',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2022-08-05',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'MAU INFUS PASIEN, ADA KECOA, KAGET, SPUILT JATUH, TERINJAK, TEMBUS',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000004',
            'kategori_cidera' => 'Berat',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 3,
            'penyebab_langsung_kondisi' => '-',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => 'D0000003',
            'perbaikan_jenis_tindakan' => 'Tindakan Pencegahan',
            'perbaikan_rencana_tindakan' => 'PEST KONTROL',
            'perbaikan_target' => '2022-08-05',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => '08998998',
            'catatan' => '-',
          ),
          6 => 
          array (
            'no_k3rs' => 'K3/2023/05/26/0001',
            'tgl_insiden' => '2023-05-26',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK002',
            'tgl_pelaporan' => '2023-05-26',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'keplaset karena lantai licin, jatuh, jatum tertusuk paha',
            'kode_penyebab' => 'PK005',
            'nik' => '08998998',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK002',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'lingkungan ',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '123124',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => '12',
            'perbaikan_target' => '2023-05-26',
            'perbaikan_wewenang' => '-',
            'nik_timk3' => '08998998',
            'catatan' => '12',
          ),
          7 => 
          array (
            'no_k3rs' => 'K3/2023/07/25/0001',
            'tgl_insiden' => '2023-07-25',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2023-07-25',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'MAU NGINFUS, KECOA LEWAT, KAGET, JARUM JATUH, TERINJAK KAKI',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000004',
            'kategori_cidera' => 'Sedang',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 2,
            'penyebab_langsung_kondisi' => 'LINGKUNGAN KOTOR',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '010101',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'DILAKUKAN PEST KONTROL',
            'perbaikan_target' => '2023-07-25',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => '12/09/1988/001',
            'catatan' => '-',
          ),
          8 => 
          array (
            'no_k3rs' => 'K3/2023/12/13/0001',
            'tgl_insiden' => '2023-12-13',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK002',
            'tgl_pelaporan' => '2023-12-13',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'habis berantem dengan suami. tidak konsen, jarum jatuh dan terinjak. ',
            'kode_penyebab' => 'PK006',
            'nik' => '08998998',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'melamun',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => 'cekcok dengan suami',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '12/09/1988/001',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'konseling SDI',
            'perbaikan_target' => '2023-12-13',
            'perbaikan_wewenang' => 'HRD',
            'nik_timk3' => 'D0000004',
            'catatan' => '-',
          ),
          9 => 
          array (
            'no_k3rs' => 'K3/2024/03/19/0001',
            'tgl_insiden' => '2024-03-19',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-03-19',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'mau infus pasien, kecoak lewat, kaget, spuit jatuh, terinjak',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000004',
            'kategori_cidera' => 'Sedang',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'ruangan kotor, tidak konsen, banyak binatang',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => 'habis berantem dengan suami, tidak konsen',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '08998998',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'kesling, pest kontrol',
            'perbaikan_target' => '2024-03-19',
            'perbaikan_wewenang' => 'kesling',
            'nik_timk3' => '123124',
            'catatan' => '-',
          ),
          10 => 
          array (
            'no_k3rs' => 'K3/2024/04/23/0001',
            'tgl_insiden' => '2024-04-23',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-04-23',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'mau nginfus, kecoak lewat, jarum jatuh, terinjak',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000003',
            'kategori_cidera' => 'Sedang',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => '-',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '010101',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => '-	',
            'perbaikan_target' => '2024-04-23',
            'perbaikan_wewenang' => '-',
            'nik_timk3' => '123124',
            'catatan' => '-',
          ),
          11 => 
          array (
            'no_k3rs' => 'K3/2024/06/05/0001',
            'tgl_insiden' => '2024-06-05',
            'waktu_insiden' => '19:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-06-05',
            'waktu_pelaporan' => '20:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'BARU MENGINFUS MELAMUN, KARENA HABIS BERANTEM DENGAN SUAMI. JARUM/SPUIT JATUH, KAGET, TERINJAK KAKI, TEMBUS SAMPAI KE ATAS',
            'kode_penyebab' => 'PK006',
            'nik' => '08998998',
            'kategori_cidera' => 'Sedang',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 3,
            'penyebab_langsung_kondisi' => 'MELAMUN',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => 'MASALAH KELUARGA',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '12/09/1988/001',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'KONSELING BAGIAN SUMBER DAYA INSANI',
            'perbaikan_target' => '2024-06-10',
            'perbaikan_wewenang' => 'BAGIAN HRD',
            'nik_timk3' => 'D0000004',
            'catatan' => 'TES',
          ),
          12 => 
          array (
            'no_k3rs' => 'K3/2024/10/11/0001',
            'tgl_insiden' => '2024-10-11',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-10-11',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'mau menginfus, kecoa lewat, kaget, spuit jatuh dan terinjak',
            'kode_penyebab' => 'PK004',
            'nik' => 'D0000004',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 3,
            'penyebab_langsung_kondisi' => '-',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '08998998',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'pest kontrol',
            'perbaikan_target' => '2024-10-11',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => '123124',
            'catatan' => 'TES',
          ),
          13 => 
          array (
            'no_k3rs' => 'K3/2024/11/12/0001',
            'tgl_insiden' => '2024-11-12',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-11-12',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'MAU MENGINFUS PASIEN, KECOA LEWAT, KAGET, JARUM JATUH DAN TERINJAK',
            'kode_penyebab' => 'PK004',
            'nik' => '123124',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'TIDAK WASPADA',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '08998998',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'KESLING MELAKUKAN PEST KONTROL',
            'perbaikan_target' => '2024-11-12',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => 'D0000004',
            'catatan' => '-',
          ),
          14 => 
          array (
            'no_k3rs' => 'K3/2024/11/25/0001',
            'tgl_insiden' => '2024-11-25',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2024-11-25',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'SAAT MENGINFUS MELAMUN, SALAH RUTE INFUS, KENA TANGAN SENDIRI',
            'kode_penyebab' => 'PK006',
            'nik' => '08998998',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'MELAMUN',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => 'KONFLIK KELUARGA',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '123124',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'KONSELING SDI',
            'perbaikan_target' => '2024-11-25',
            'perbaikan_wewenang' => 'SDI',
            'nik_timk3' => 'D0000004',
            'catatan' => '-',
          ),
          15 => 
          array (
            'no_k3rs' => 'K3/2025/08/25/0001',
            'tgl_insiden' => '2025-08-25',
            'waktu_insiden' => '00:00:00',
            'kode_pekerjaan' => 'PK003',
            'tgl_pelaporan' => '2025-08-25',
            'waktu_pelaporan' => '00:00:00',
            'kode_lokasi' => 'LK001',
            'kronologi_kejadian' => 'MAU INFUS PASIEN KECOAK LEWAT, KAGET, JARUM JATUH TERINJAK KAKI',
            'kode_penyebab' => 'PK004',
            'nik' => '01010101',
            'kategori_cidera' => 'Ringan',
            'kode_cidera' => 'CK004',
            'kode_luka' => 'LK001',
            'kode_bagian' => 'BK005',
            'lt' => 0,
            'penyebab_langsung_kondisi' => 'KAGET, TIDAK WASPADA',
            'penyebab_langsung_tindakan' => '-',
            'penyebab_tidak_langsung_pribadi' => '-',
            'penyebab_tidak_langsung_pekerjaan' => '-',
            'barang_bukti' => 'Ya',
            'kode_dampak' => 'DK001',
            'nik_pelapor' => '156798',
            'perbaikan_jenis_tindakan' => 'Tindakan Perbaikan',
            'perbaikan_rencana_tindakan' => 'PES KONTROL',
            'perbaikan_target' => '2025-08-25',
            'perbaikan_wewenang' => 'KESLING',
            'nik_timk3' => 'D0000004',
            'catatan' => '-',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}