<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PasienBayiTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('pasien_bayi')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('pasien_bayi')->insert([
            0 => [
                'no_rkm_medis' => '000006',
                'umur_ibu' => '33',
                'nama_ayah' => 'WINDIARTO',
                'umur_ayah' => '34',
                'berat_badan' => '340',
                'panjang_badan' => '51',
                'lingkar_kepala' => '20',
                'proses_lahir' => '-',
                'anakke' => '2',
                'jam_lahir' => '00:00:00',
                'keterangan' => '-',
                'diagnosa' => '-',
                'penyulit_kehamilan' => '-',
                'ketuban' => '-',
                'lingkar_perut' => '20',
                'lingkar_dada' => '20',
                'penolong' => 'D0000004',
                'no_skl' => '0001/RM-SKL/08/2022',
                'g' => '-',
                'p' => '-',
                'a' => '-',
                'f1' => '2',
                'u1' => '2',
                't1' => '2',
                'r1' => '2',
                'w1' => '2',
                'n1' => '10',
                'f5' => '2',
                'u5' => '2',
                't5' => '2',
                'r5' => '2',
                'w5' => '2',
                'n5' => '10',
                'f10' => '2',
                'u10' => '2',
                't10' => '2',
                'r10' => '2',
                'w10' => '2',
                'n10' => '10',
                'resusitas' => '-',
                'obat_diberikan' => '-',
                'mikasi' => '-',
                'mikonium' => '-',
            ],
            1 => [
                'no_rkm_medis' => '000014',
                'umur_ibu' => '25',
                'nama_ayah' => 'WAWAN',
                'umur_ayah' => '26',
                'berat_badan' => '2500',
                'panjang_badan' => '50',
                'lingkar_kepala' => '30',
                'proses_lahir' => '-',
                'anakke' => '2',
                'jam_lahir' => '00:00:00',
                'keterangan' => '-',
                'diagnosa' => '-',
                'penyulit_kehamilan' => '-',
                'ketuban' => '-',
                'lingkar_perut' => '30',
                'lingkar_dada' => '30',
                'penolong' => 'D0000003',
                'no_skl' => '0001/RM-SKL/05/2023',
                'g' => '',
                'p' => '',
                'a' => '',
                'f1' => '1',
                'u1' => '2',
                't1' => '2',
                'r1' => '2',
                'w1' => '2',
                'n1' => '9',
                'f5' => '1',
                'u5' => '2',
                't5' => '2',
                'r5' => '2',
                'w5' => '2',
                'n5' => '9',
                'f10' => '1',
                'u10' => '2',
                't10' => '2',
                'r10' => '2',
                'w10' => '2',
                'n10' => '9',
                'resusitas' => '',
                'obat_diberikan' => '',
                'mikasi' => '',
                'mikonium' => '',
            ],
            2 => [
                'no_rkm_medis' => '000052',
                'umur_ibu' => '23',
                'nama_ayah' => 'IRFAN',
                'umur_ayah' => '24',
                'berat_badan' => '3200',
                'panjang_badan' => '51',
                'lingkar_kepala' => '33',
                'proses_lahir' => '-',
                'anakke' => '3',
                'jam_lahir' => '00:00:00',
                'keterangan' => '-',
                'diagnosa' => '--',
                'penyulit_kehamilan' => '-',
                'ketuban' => '-',
                'lingkar_perut' => '-',
                'lingkar_dada' => '34',
                'penolong' => 'D0000004',
                'no_skl' => '0001/RM-SKL/08/2025',
                'g' => '0',
                'p' => '00',
                'a' => '0',
                'f1' => '5',
                'u1' => '5',
                't1' => '5',
                'r1' => '5',
                'w1' => '5',
                'n1' => '25',
                'f5' => '5',
                'u5' => '5',
                't5' => '5',
                'r5' => '5',
                'w5' => '5',
                'n5' => '25',
                'f10' => '5',
                'u10' => '5',
                't10' => '5',
                'r10' => '5',
                'w10' => '5',
                'n10' => '25',
                'resusitas' => '-',
                'obat_diberikan' => '-',
                'mikasi' => '-',
                'mikonium' => '',
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
