<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PcareRujukSubspesialiTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('pcare_rujuk_subspesialis')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('pcare_rujuk_subspesialis')->insert([
            0 => [
                'no_rawat' => '2025/11/12/000001',
                'noKunjungan' => null,
                'tglDaftar' => '2025-11-12',
                'no_rkm_medis' => '000057',
                'nm_pasien' => 'AGUS BUDIYONO,A. Md.Kep',
                'noKartu' => '0001441909697',
                'kdPoli' => '001',
                'nmPoli' => null,
                'keluhan' => 'Pasien melakukan kontrol rutin.',
                'kdSadar' => null,
                'nmSadar' => null,
                'sistole' => null,
                'diastole' => null,
                'beratBadan' => null,
                'tinggiBadan' => null,
                'respRate' => null,
                'heartRate' => null,
                'lingkarPerut' => '',
                'terapi' => null,
                'kdStatusPulang' => null,
                'nmStatusPulang' => null,
                'tglPulang' => null,
                'kdDokter' => '132183',
                'nmDokter' => null,
                'kdDiag1' => 'H52.5',
                'nmDiag1' => null,
                'kdDiag2' => null,
                'nmDiag2' => null,
                'kdDiag3' => null,
                'nmDiag3' => null,
                'tglEstRujuk' => '2025-11-12',
                'kdPPK' => '0154R010',
                'nmPPK' => '',
                'kdSubSpesialis' => null,
                'nmSubSpesialis' => null,
                'kdSarana' => '1',
                'nmSarana' => null,
                'kdTACC' => '0',
                'nmTACC' => null,
                'alasanTACC' => null,
                'KdAlergiMakanan' => '',
                'NmAlergiMakanan' => '',
                'KdAlergiUdara' => '',
                'NmAlergiUdara' => '',
                'KdAlergiObat' => '',
                'NmAlergiObat' => '',
                'KdPrognosa' => '',
                'NmPrognosa' => '',
                'terapi_non_obat' => '',
                'bmhp' => '',
            ],
            1 => [
                'no_rawat' => '2025/11/13/000001',
                'noKunjungan' => '112516161125Y001193',
                'tglDaftar' => '2025-11-13',
                'no_rkm_medis' => '000057',
                'nm_pasien' => 'AGUS BUDIYONO,A. Md.Kep',
                'noKartu' => '0001441909697',
                'kdPoli' => 'U0009',
                'nmPoli' => null,
                'keluhan' => null,
                'kdSadar' => null,
                'nmSadar' => null,
                'sistole' => null,
                'diastole' => null,
                'beratBadan' => null,
                'tinggiBadan' => null,
                'respRate' => null,
                'heartRate' => null,
                'lingkarPerut' => '',
                'terapi' => null,
                'kdStatusPulang' => '4',
                'nmStatusPulang' => null,
                'tglPulang' => null,
                'kdDokter' => 'D0000002',
                'nmDokter' => null,
                'kdDiag1' => 'H52.5',
                'nmDiag1' => null,
                'kdDiag2' => null,
                'nmDiag2' => null,
                'kdDiag3' => null,
                'nmDiag3' => null,
                'tglEstRujuk' => '2025-11-20',
                'kdPPK' => '11251616',
                'nmPPK' => '',
                'kdSubSpesialis' => '65',
                'nmSubSpesialis' => null,
                'kdSarana' => '1',
                'nmSarana' => null,
                'kdTACC' => null,
                'nmTACC' => null,
                'alasanTACC' => null,
                'KdAlergiMakanan' => '',
                'NmAlergiMakanan' => '',
                'KdAlergiUdara' => '',
                'NmAlergiUdara' => '',
                'KdAlergiObat' => '',
                'NmAlergiObat' => '',
                'KdPrognosa' => '',
                'NmPrognosa' => '',
                'terapi_non_obat' => '',
                'bmhp' => '',
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
