<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PemeriksaanRalanTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('pemeriksaan_ralan')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('pemeriksaan_ralan')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/04/27/000001',
            'tgl_perawatan' => '2025-04-27',
            'jam_rawat' => '08:32:31',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'asas',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          1 => 
          array (
            'no_rawat' => '2025/04/27/000001',
            'tgl_perawatan' => '2025-04-27',
            'jam_rawat' => '08:36:58',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'pasien mengeluh menggigil',
            'pemeriksaan' => 'mata merah, akral dingin',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen 200 mg Jumlah 10.0 Aturan Pakai 2 x 1
        ',
            'penilaian' => 'thyphoid',
            'instruksi' => 'cek lab',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          2 => 
          array (
            'no_rawat' => '2025/04/27/000002',
            'tgl_perawatan' => '2025-04-27',
            'jam_rawat' => '08:29:59',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Tes',
            'pemeriksaan' => 'sasss',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'asas',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          3 => 
          array (
            'no_rawat' => '2025/04/27/000002',
            'tgl_perawatan' => '2025-04-27',
            'jam_rawat' => '08:30:30',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Tes',
            'pemeriksaan' => 'sasss',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'asas',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          4 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'tgl_perawatan' => '2025-05-26',
            'jam_rawat' => '10:19:46',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'SUBJECK',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          5 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'tgl_perawatan' => '2025-05-26',
            'jam_rawat' => '10:20:29',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'asas',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          6 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'tgl_perawatan' => '2025-05-26',
            'jam_rawat' => '10:27:31',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'subject',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          7 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'tgl_perawatan' => '2025-05-26',
            'jam_rawat' => '10:27:42',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'pasien mengeluh menggigil',
            'pemeriksaan' => 'mata merah, akral dingin',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen 200 mg Jumlah 10.0 Aturan Pakai 2 x 1
        ',
            'penilaian' => 'thyphoid',
            'instruksi' => 'cek lab',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          8 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'tgl_perawatan' => '2025-05-26',
            'jam_rawat' => '10:28:19',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'qwqwqw',
            'pemeriksaan' => 'wqwqw',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'qwqwqw Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2 x1
        Amoxsan 500 mg  Jumlah 10 Aturan Pakai 3 x 1
        1. R1 Jumlah 13 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 8.7
        -- Acrios 50 mg tab 7.3
         Resep : 
        Amoxsan 500 mg  Jumlah 10 Aturan Pakai 3 x 1
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2 x1
        1. R1 Jumlah 13 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 8.7
        -- Acrios 50 mg tab 7.3
        ',
            'penilaian' => 'PENYAKIT JANTUNG',
            'instruksi' => 'wqwqw',
            'evaluasi' => 'qwqw',
            'nip' => 'D0000004',
          ),
          9 => 
          array (
            'no_rawat' => '2025/06/03/000003',
            'tgl_perawatan' => '2025-06-03',
            'jam_rawat' => '09:34:05',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'PAKET MCU 15 ORANG',
            'pemeriksaan' => '1212',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '121212',
            'penilaian' => '1212',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          10 => 
          array (
            'no_rawat' => '2025/06/09/000002',
            'tgl_perawatan' => '2025-06-09',
            'jam_rawat' => '08:40:34',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => '1212',
            'pemeriksaan' => '121212',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '212',
            'penilaian' => '21212',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          11 => 
          array (
            'no_rawat' => '2025/06/11/000001',
            'tgl_perawatan' => '2025-06-11',
            'jam_rawat' => '19:32:54',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'MUAL, MUNTAH, NYERI DADA',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'TYPOID FEVER',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          12 => 
          array (
            'no_rawat' => '2025/06/18/000001',
            'tgl_perawatan' => '2025-06-18',
            'jam_rawat' => '13:18:24',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => '-',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '-',
            'penilaian' => '-',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000005',
          ),
          13 => 
          array (
            'no_rawat' => '2025/06/18/000002',
            'tgl_perawatan' => '2025-06-18',
            'jam_rawat' => '12:57:49',
            'suhu_tubuh' => 'qwqw',
            'tensi' => 'wqw',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'wqw',
            'pemeriksaan' => 'qwqw',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          14 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'tgl_perawatan' => '2025-06-20',
            'jam_rawat' => '09:55:26',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'MUAL, MUNTAH, NYERI DADA ggg',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'TYPOID FEVER',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          15 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'tgl_perawatan' => '2025-06-20',
            'jam_rawat' => '13:54:45',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'qwqwqw',
            'pemeriksaan' => 'wqwqw',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen syr 100 mg Jumlah 1 Aturan Pakai 3 x 1
        1. R1 Jumlah 10 Puyer Aturan Pakai 3 x 1
        -- Acyclovir 200 mg Tablet 6.7
        -- Albendazole tab 9.2
         Resep : 
        Amoxsan 500 mg  Jumlah 10 Aturan Pakai 3 x 1
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2 x1
        1. R1 Jumlah 13 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 8.7
        -- Acrios 50 mg tab 7.3
        ',
            'penilaian' => 'PENYAKIT JANTUNG',
            'instruksi' => 'wqwqw',
            'evaluasi' => 'qwqw',
            'nip' => 'D0000004',
          ),
          16 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'tgl_perawatan' => '2025-06-20',
            'jam_rawat' => '14:01:48',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI Resep : 
        AB-Vask 10mg (Otsus) Jumlah 10 Aturan Pakai 2 x 1
        ',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          17 => 
          array (
            'no_rawat' => '2025/06/23/000001',
            'tgl_perawatan' => '2025-06-23',
            'jam_rawat' => '10:57:19',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          18 => 
          array (
            'no_rawat' => '2025/06/25/000001',
            'tgl_perawatan' => '2025-06-25',
            'jam_rawat' => '08:59:38',
            'suhu_tubuh' => '-',
            'tensi' => '-',
            'nadi' => '-',
            'respirasi' => '-',
            'tinggi' => '-',
            'berat' => '-',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'tes',
            'pemeriksaan' => 'tes',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          19 => 
          array (
            'no_rawat' => '2025/06/25/000001',
            'tgl_perawatan' => '2025-06-25',
            'jam_rawat' => '09:00:39',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'tes',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          20 => 
          array (
            'no_rawat' => '2025/06/25/000001',
            'tgl_perawatan' => '2025-06-28',
            'jam_rawat' => '11:10:55',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          21 => 
          array (
            'no_rawat' => '2025/06/30/000003',
            'tgl_perawatan' => '2025-06-30',
            'jam_rawat' => '08:56:01',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'TES',
            'pemeriksaan' => 'TES',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          22 => 
          array (
            'no_rawat' => '2025/06/30/000003',
            'tgl_perawatan' => '2025-06-30',
            'jam_rawat' => '08:56:18',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'asas',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          23 => 
          array (
            'no_rawat' => '2025/06/30/000003',
            'tgl_perawatan' => '2025-06-30',
            'jam_rawat' => '09:18:07',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'TES',
            'pemeriksaan' => 'TES',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2 X 1
        Paracetamol 500 mg Jumlah 10 Aturan Pakai 2 X 1
        1. R1 Jumlah 10 Puyer Aturan Pakai 2 X 1
        -- Acetensa tab 6.4
        -- Acran 150 mg Tablet 6.7
         Resep : 
        Amoxsan 500 mg  Jumlah 10 Aturan Pakai 3 x 1
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2 x1
        1. R1 Jumlah 13 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 8.7
        -- Acrios 50 mg tab 7.3
        ',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          24 => 
          array (
            'no_rawat' => '2025/07/04/000001',
            'tgl_perawatan' => '2025-07-04',
            'jam_rawat' => '13:39:31',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'MUAL, MUNTAH, NYERI DADA',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'TYPOID FEVER',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          25 => 
          array (
            'no_rawat' => '2025/07/05/000001',
            'tgl_perawatan' => '2025-07-05',
            'jam_rawat' => '20:13:41',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'MUAL, MUNTAH, NYERI DADA',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'TYPOID FEVER',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          26 => 
          array (
            'no_rawat' => '2025/07/05/000001',
            'tgl_perawatan' => '2025-07-07',
            'jam_rawat' => '08:52:07',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          27 => 
          array (
            'no_rawat' => '2025/07/07/000001',
            'tgl_perawatan' => '2025-07-07',
            'jam_rawat' => '08:52:07',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'MUAL, MUNTAH, NYERI DADA',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => 'TYPOID FEVER',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          28 => 
          array (
            'no_rawat' => '2025/07/14/000001',
            'tgl_perawatan' => '2025-07-14',
            'jam_rawat' => '16:32:43',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'tes',
            'pemeriksaan' => 'tes',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'y Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 1 x 2
        ',
            'penilaian' => 't',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          29 => 
          array (
            'no_rawat' => '2025/07/14/000001',
            'tgl_perawatan' => '2025-07-14',
            'jam_rawat' => '16:45:25',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'qwqwqw',
            'pemeriksaan' => 'wqwqw',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'qwqwqw',
            'penilaian' => 'PENYAKIT JANTUNG',
            'instruksi' => 'wqwqw',
            'evaluasi' => 'qwqw',
            'nip' => 'D0000004',
          ),
          30 => 
          array (
            'no_rawat' => '2025/07/21/000001',
            'tgl_perawatan' => '2025-07-21',
            'jam_rawat' => '09:09:02',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          31 => 
          array (
            'no_rawat' => '2025/07/23/000001',
            'tgl_perawatan' => '2025-07-23',
            'jam_rawat' => '14:23:00',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          32 => 
          array (
            'no_rawat' => '2025/07/23/000001',
            'tgl_perawatan' => '2025-07-23',
            'jam_rawat' => '14:23:23',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'sasas',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'asas Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai  2 x 1
        Paracetamol 500 mg Jumlah 10 Aturan Pakai 3x 1
        1. R1 Jumlah 14 Puyer Aturan Pakai 3 x 1
        -- Acran 150 mg Tablet 9.3
        -- Acyclovir 200 mg Tablet 11
        ',
            'penilaian' => 'sasas',
            'instruksi' => 'asas',
            'evaluasi' => 'as',
            'nip' => 'D0000004',
          ),
          33 => 
          array (
            'no_rawat' => '2025/07/29/000001',
            'tgl_perawatan' => '2025-07-29',
            'jam_rawat' => '09:23:06',
            'suhu_tubuh' => '1212',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => '121',
            'pemeriksaan' => '1212',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '212',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '08998998',
          ),
          34 => 
          array (
            'no_rawat' => '2025/07/29/000001',
            'tgl_perawatan' => '2025-07-29',
            'jam_rawat' => '09:29:16',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => 'wqwqw',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'qwqw',
            'pemeriksaan' => 'qwqw',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2x1
        Paracetamol 500 mg Jumlah 10 Aturan Pakai 3x1
        1. R1 Jumlah 14 Puyer Aturan Pakai 3 x 1
        -- Acran 150 mg Tablet 8.1
        -- Acyclovir 200 mg Tablet 9.3
        ',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          35 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'tgl_perawatan' => '2025-08-04',
            'jam_rawat' => '09:29:43',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          36 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'tgl_perawatan' => '2025-08-04',
            'jam_rawat' => '10:06:32',
            'suhu_tubuh' => 'asas',
            'tensi' => 'sasas',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Sasas',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'asas Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2x 1
        Amlodipine 10 mg Jumlah 10 Aturan Pakai 3x1
        1. R1 Jumlah 14 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 9.3
        -- Acrios 50 mg tab 9.8
         Resep : 
        Amlodipine 10 mg Jumlah 10 Aturan Pakai 2x1
        ',
            'penilaian' => 'sasas',
            'instruksi' => '',
            'evaluasi' => 'sasas',
            'nip' => 'D0000004',
          ),
          37 => 
          array (
            'no_rawat' => '2025/08/11/000001',
            'tgl_perawatan' => '2025-08-11',
            'jam_rawat' => '14:09:13',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => '1212',
            'pemeriksaan' => '12121',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '1212',
            'penilaian' => '21212',
            'instruksi' => '1212',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          38 => 
          array (
            'no_rawat' => '2025/08/11/000001',
            'tgl_perawatan' => '2025-08-11',
            'jam_rawat' => '14:09:34',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => '1212',
            'pemeriksaan' => '12121',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '1212',
            'penilaian' => '21212',
            'instruksi' => '1212',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          39 => 
          array (
            'no_rawat' => '2025/08/11/000001',
            'tgl_perawatan' => '2025-08-11',
            'jam_rawat' => '14:19:44',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          40 => 
          array (
            'no_rawat' => '2025/08/19/000001',
            'tgl_perawatan' => '2025-08-19',
            'jam_rawat' => '09:56:55',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'e',
            'pemeriksaan' => '',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'o',
            'penilaian' => 'j',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          41 => 
          array (
            'no_rawat' => '2025/08/19/000001',
            'tgl_perawatan' => '2025-08-19',
            'jam_rawat' => '09:57:09',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'asas',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          42 => 
          array (
            'no_rawat' => '2025/08/19/000001',
            'tgl_perawatan' => '2025-08-19',
            'jam_rawat' => '10:02:26',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'PAKET MCU 15 ORANG',
            'pemeriksaan' => '1212',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '121212',
            'penilaian' => '1212',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          43 => 
          array (
            'no_rawat' => '2025/08/21/000001',
            'tgl_perawatan' => '2025-08-21',
            'jam_rawat' => '14:37:03',
            'suhu_tubuh' => 'sas',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'sasas',
            'pemeriksaan' => 'asas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'asas',
            'penilaian' => 'sasas',
            'instruksi' => 'asas',
            'evaluasi' => '',
            'nip' => '123124',
          ),
          44 => 
          array (
            'no_rawat' => '2025/08/21/000001',
            'tgl_perawatan' => '2025-08-21',
            'jam_rawat' => '14:45:25',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'sasssa',
            'pemeriksaan' => 'sasas',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => ' Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 3x1
        Amlodipine 5 mg Jumlah 10 Aturan Pakai 2x1
        1. R1 Jumlah 12 Puyer Aturan Pakai 3 x 1
        -- Acran 150 mg Tablet 8
        -- Acyclovir 200 mg Tablet 7.2
        ',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          45 => 
          array (
            'no_rawat' => '2025/08/25/000001',
            'tgl_perawatan' => '2025-08-25',
            'jam_rawat' => '11:21:39',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'SJJJ',
            'pemeriksaan' => '8L',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => '',
            'penilaian' => '',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => '156798',
          ),
          46 => 
          array (
            'no_rawat' => '2025/08/25/000001',
            'tgl_perawatan' => '2025-08-25',
            'jam_rawat' => '13:13:48',
            'suhu_tubuh' => '',
            'tensi' => '',
            'nadi' => '',
            'respirasi' => '',
            'tinggi' => '',
            'berat' => '',
            'spo2' => '',
            'gcs' => '',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'NYERI DADA SEBELAH KIRI',
            'pemeriksaan' => 'SUHU : 37',
            'alergi' => '',
            'lingkar_perut' => '',
            'rtl' => 'LAB, RADIOLOGI Resep : 
        Ibuprofen 400 mg Jumlah 10 Aturan Pakai 2x1
        Amlodipine 10 mg Jumlah 10 Aturan Pakai 3 x 1
         Resep : 
        1. R BATUK Jumlah 12 Puyer Aturan Pakai 2 X 1
        -- Acyclovir 200 mg Tablet 8
        -- Afamed tab 6
        2. R ANTIBIO Jumlah 13 Puyer Aturan Pakai 3 x 1
        -- Acetensa tab 8
        -- Amoxsan 500 mg  5.8
        ',
            'penilaian' => 'TYPHOID',
            'instruksi' => '',
            'evaluasi' => '',
            'nip' => 'D0000004',
          ),
          47 => 
          array (
            'no_rawat' => '2025/11/12/000001',
            'tgl_perawatan' => '2025-11-12',
            'jam_rawat' => '09:37:00',
            'suhu_tubuh' => '36.5',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '89',
            'spo2' => '96',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien melakukan kontrol rutin.',
            'pemeriksaan' => 'Keadaan Umum : Baik, Composmentis
        Thorax : Cor S1-2 intensitas normal, reguler, bising (-)
        Pulmo : SDV +/+ ST -/-
        Abdomen : Supel, NT(-), peristaltik (+) normal.
        EXT : Oedem -/-',
            'alergi' => 'Paracetamol',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi Kesehatan',
            'penilaian' => 'Kondisi pasien stabil',
            'instruksi' => 'Istirahat Cukup, PHBS',
            'evaluasi' => 'Kontrol Ulang Jika belum Ada Perubahan',
            'nip' => 'D0000002',
          ),
          48 => 
          array (
            'no_rawat' => '2025/11/12/000002',
            'tgl_perawatan' => '2025-11-12',
            'jam_rawat' => '21:24:00',
            'suhu_tubuh' => '36.5',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => '140',
            'berat' => '45',
            'spo2' => '96',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien melakukan kontrol rutin.',
            'pemeriksaan' => 'Keadaan Umum : Baik, Composmentis
        Thorax : Cor S1-2 intensitas normal, reguler, bising (-)
        Pulmo : SDV +/+ ST -/-
        Abdomen : Supel, NT(-), peristaltik (+) normal.
        EXT : Oedem -/-',
            'alergi' => '-',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi Kesehatan',
            'penilaian' => 'Kondisi pasien stabil',
            'instruksi' => 'Istirahat Cukup, PHBS',
            'evaluasi' => 'Kontrol Ulang Jika belum Ada Perubahan',
            'nip' => 'D0000002',
          ),
          49 => 
          array (
            'no_rawat' => '2025/11/13/000001',
            'tgl_perawatan' => '2025-11-13',
            'jam_rawat' => '19:06:00',
            'suhu_tubuh' => '36.8',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => NULL,
            'berat' => NULL,
            'spo2' => '98',
            'gcs' => NULL,
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien datang dengan keluhan yang konsisten dengan Mata Kering. Keluhan dirasakan sejak ±3 hari terakhir, intensitas ringan–sedang, kadang mengganggu aktivitas harian. Pasien tidak melaporkan tanda bahaya (mis. demam tinggi menetap, perdarahan, nyeri hebat progresif, penurunan kesadaran).',
            'pemeriksaan' => 'Keadaan umum baik, kesadaran Compos Mentis. TD 120/80 mmHg; Nadi 80 x/menit; RR 20 x/menit; Suhu 36.8°C; SpO2 98%. Pemeriksaan fisik sesuai kebutuhan klinis dan temuan khas.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => NULL,
            'rtl' => 'Tatalaksana simptomatik/spesifik dan edukasi sesuai PPK/BPJS untuk kondisi: Mata Kering.',
            'penilaian' => 'Mata Kering',
            'instruksi' => 'Kontrol bila keluhan memburuk atau tidak membaik; patuhi terapi dan edukasi yang diberikan.',
            'evaluasi' => 'Evaluasi respons terapi pada kunjungan berikutnya dan sesuaikan bila perlu.',
            'nip' => 'D0000002',
          ),
          50 => 
          array (
            'no_rawat' => '2025/11/15/000001',
            'tgl_perawatan' => '2025-11-15',
            'jam_rawat' => '15:27:00',
            'suhu_tubuh' => '36.5',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '80',
            'spo2' => '96',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien melakukan kontrol rutin.',
            'pemeriksaan' => 'Keadaan Umum : Baik, Composmentis
        Thorax : Cor S1-2 intensitas normal, reguler, bising (-)
        Pulmo : SDV +/+ ST -/-
        Abdomen : Supel, NT(-), peristaltik (+) normal.
        EXT : Oedem -/-',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi Kesehatan',
            'penilaian' => 'Kondisi pasien stabil',
            'instruksi' => 'Istirahat Cukup, PHBS',
            'evaluasi' => 'Kontrol Ulang Jika belum Ada Perubahan',
            'nip' => 'D0000002',
          ),
          51 => 
          array (
            'no_rawat' => '2025/11/22/000001',
            'tgl_perawatan' => '2025-11-22',
            'jam_rawat' => '17:16:00',
            'suhu_tubuh' => '36.8',
            'tensi' => '150/95',
            'nadi' => '85',
            'respirasi' => '18',
            'tinggi' => '165',
            'berat' => '90',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah beberapa minggu mengeluh pusing/sakit kepala, kadang berdebar. Riwayat tekanan darah tinggi.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 150/95 mmHg; Nadi 85 x/menit reguler; RR 18 x/menit; Suhu 36.8°C; SpO2 98%. Tidak ada distress napas, JVP normal, edema tungkai (-), bunyi jantung normal.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '80',
            'rtl' => 'Edukasi diet rendah garam, olahraga teratur, monitoring tekanan darah. Terapi antihipertensi sesuai resep dan kontrol berkala.',
            'penilaian' => 'Hipertensi esensial (ICD-10: I10).',
            'instruksi' => 'Pantau tekanan darah di rumah, hindari rokok/kafein.',
            'evaluasi' => 'Rencana kontrol 1-2 minggu untuk evaluasi TD dan gejala.',
            'nip' => '19830112',
          ),
          52 => 
          array (
            'no_rawat' => '2025/11/23/000001',
            'tgl_perawatan' => '2025-11-23',
            'jam_rawat' => '21:19:00',
            'suhu_tubuh' => '38.5',
            'tensi' => '120/80',
            'nadi' => '95',
            'respirasi' => '22',
            'tinggi' => '165',
            'berat' => '80',
            'spo2' => '97',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 3 hari mengeluh demam, batuk, nyeri tenggorokan, pegal-pegal, pilek.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 120/80 mmHg; Nadi 95 x/menit; RR 22 x/menit; Suhu 38.5°C; SpO2 97%. Rinorea (+), faring hiperemis, ronkhi (-), wheezing (-).',
            'alergi' => 'Paracetamool',
            'lingkar_perut' => '72',
            'rtl' => 'Istirahat, hidrasi cukup, antipiretik, vitamin, terapi simptomatik. Anjuran masker dan etika batuk.',
            'penilaian' => 'Influenza (ICD-10: J10/J11).',
            'instruksi' => 'Pantau suhu; bila sesak atau saturasi <94% segera ke IGD.',
            'evaluasi' => 'Kontrol 3-5 hari bila belum membaik atau muncul tanda bahaya.',
            'nip' => '19830112',
          ),
          53 => 
          array (
            'no_rawat' => '2025/11/25/000001',
            'tgl_perawatan' => '2025-11-25',
            'jam_rawat' => '12:54:00',
            'suhu_tubuh' => '36.5',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => '176',
            'berat' => '67',
            'spo2' => '96',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien melakukan kontrol rutin.',
            'pemeriksaan' => 'Keadaan Umum : Baik, Composmentis
        Thorax : Cor S1-2 intensitas normal, reguler, bising (-)
        Pulmo : SDV +/+ ST -/-
        Abdomen : Supel, NT(-), peristaltik (+) normal.
        EXT : Oedem -/-',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi Kesehatan',
            'penilaian' => 'Kondisi pasien stabil',
            'instruksi' => 'Istirahat Cukup, PHBS',
            'evaluasi' => 'Kontrol Ulang Jika belum Ada Perubahan',
            'nip' => '19830112',
          ),
          54 => 
          array (
            'no_rawat' => '2025/11/27/000001',
            'tgl_perawatan' => '2025-11-27',
            'jam_rawat' => '09:23:00',
            'suhu_tubuh' => '38.0',
            'tensi' => '120/80',
            'nadi' => '90',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 2-3 hari nyeri tenggorokan, nyeri saat menelan, demam ringan, tanpa sesak.',
            'pemeriksaan' => 'CM; TD 120/80; N 90; RR 20; Suhu 38.0°C; SpO2 98%. Faring hiperemis, eksudat (-), nyeri tekan kelenjar servikal anterior ringan.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '80',
            'rtl' => 'Simptomatik (analgesik/antipiretik, kumur air garam), edukasi; pertimbangkan antibiotik bila kriteria klinis terpenuhi.',
            'penilaian' => 'Faringitis akut (ICD-10: J02).',
            'instruksi' => 'Minum hangat, istirahat, hindari iritan. Kembali bila muncul sesak, disfagia berat, atau demam tinggi.',
            'evaluasi' => 'Kontrol 2-3 hari bila belum membaik.',
            'nip' => '19830112',
          ),
          55 => 
          array (
            'no_rawat' => '2025/11/28/000001',
            'tgl_perawatan' => '2025-11-27',
            'jam_rawat' => '00:35:00',
            'suhu_tubuh' => '36.5',
            'tensi' => '120/80',
            'nadi' => '80',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '96',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien melakukan kontrol rutin.',
            'pemeriksaan' => 'Keadaan Umum : Baik, Composmentis
        Thorax : Cor S1-2 intensitas normal, reguler, bising (-)
        Pulmo : SDV +/+ ST -/-
        Abdomen : Supel, NT(-), peristaltik (+) normal.
        EXT : Oedem -/-',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi Kesehatan',
            'penilaian' => 'Kondisi pasien stabil',
            'instruksi' => 'Istirahat Cukup, PHBS',
            'evaluasi' => 'Kontrol Ulang Jika belum Ada Perubahan',
            'nip' => '12/09/1988/001',
          ),
          56 => 
          array (
            'no_rawat' => '2025/11/30/000002',
            'tgl_perawatan' => '2025-11-30',
            'jam_rawat' => '22:24:00',
            'suhu_tubuh' => '38.0',
            'tensi' => '120/80',
            'nadi' => '90',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 2-3 hari nyeri tenggorokan, nyeri saat menelan, demam ringan, tanpa sesak.',
            'pemeriksaan' => 'CM; TD 120/80; N 90; RR 20; Suhu 38.0°C; SpO2 98%. Faring hiperemis, eksudat (-), nyeri tekan kelenjar servikal anterior ringan.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Simptomatik (analgesik/antipiretik, kumur air garam), edukasi; pertimbangkan antibiotik bila kriteria klinis terpenuhi.',
            'penilaian' => 'Faringitis akut (ICD-10: J02).',
            'instruksi' => 'Minum hangat, istirahat, hindari iritan. Kembali bila muncul sesak, disfagia berat, atau demam tinggi.',
            'evaluasi' => 'Kontrol 2-3 hari bila belum membaik.',
            'nip' => '19830112',
          ),
          57 => 
          array (
            'no_rawat' => '2025/12/01/000001',
            'tgl_perawatan' => '2025-11-30',
            'jam_rawat' => '01:13:00',
            'suhu_tubuh' => '38.0',
            'tensi' => '120/80',
            'nadi' => '90',
            'respirasi' => '20',
            'tinggi' => '165',
            'berat' => '80',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 2-3 hari nyeri tenggorokan, nyeri saat menelan, demam ringan, tanpa sesak.',
            'pemeriksaan' => 'CM; TD 120/80; N 90; RR 20; Suhu 38.0°C; SpO2 98%. Faring hiperemis, eksudat (-), nyeri tekan kelenjar servikal anterior ringan.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Simptomatik (analgesik/antipiretik, kumur air garam), edukasi; pertimbangkan antibiotik bila kriteria klinis terpenuhi.',
            'penilaian' => 'Faringitis akut (ICD-10: J02).',
            'instruksi' => 'Minum hangat, istirahat, hindari iritan. Kembali bila muncul sesak, disfagia berat, atau demam tinggi.',
            'evaluasi' => 'Kontrol 2-3 hari bila belum membaik.',
            'nip' => '19830112',
          ),
          58 => 
          array (
            'no_rawat' => '2025/12/01/000002',
            'tgl_perawatan' => '2025-12-01',
            'jam_rawat' => '10:20:00',
            'suhu_tubuh' => '38.5',
            'tensi' => '120/80',
            'nadi' => '95',
            'respirasi' => '22',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '97',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 3 hari mengeluh demam, batuk, nyeri tenggorokan, pegal-pegal, pilek.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 120/80 mmHg; Nadi 95 x/menit; RR 22 x/menit; Suhu 38.5°C; SpO2 97%. Rinorea (+), faring hiperemis, ronkhi (-), wheezing (-).',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Istirahat, hidrasi cukup, antipiretik, vitamin, terapi simptomatik. Anjuran masker dan etika batuk.',
            'penilaian' => 'Influenza (ICD-10: J10/J11).',
            'instruksi' => 'Pantau suhu; bila sesak atau saturasi <94% segera ke IGD.',
            'evaluasi' => 'Kontrol 3-5 hari bila belum membaik atau muncul tanda bahaya.',
            'nip' => '19830112',
          ),
          59 => 
          array (
            'no_rawat' => '2025/12/01/000003',
            'tgl_perawatan' => '2025-12-01',
            'jam_rawat' => '12:25:00',
            'suhu_tubuh' => '36.8',
            'tensi' => '150/95',
            'nadi' => '85',
            'respirasi' => '18',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah beberapa minggu mengeluh pusing/sakit kepala, kadang berdebar. Riwayat tekanan darah tinggi.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 150/95 mmHg; Nadi 85 x/menit reguler; RR 18 x/menit; Suhu 36.8°C; SpO2 98%. Tidak ada distress napas, JVP normal, edema tungkai (-), bunyi jantung normal.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi diet rendah garam, olahraga teratur, monitoring tekanan darah. Terapi antihipertensi sesuai resep dan kontrol berkala.',
            'penilaian' => 'Hipertensi esensial (ICD-10: I10).',
            'instruksi' => 'Pantau tekanan darah di rumah, hindari rokok/kafein.',
            'evaluasi' => 'Rencana kontrol 1-2 minggu untuk evaluasi TD dan gejala.',
            'nip' => '19830112',
          ),
          60 => 
          array (
            'no_rawat' => '2025/12/01/000004',
            'tgl_perawatan' => '2025-12-01',
            'jam_rawat' => '22:07:00',
            'suhu_tubuh' => '38.5',
            'tensi' => '120/80',
            'nadi' => '95',
            'respirasi' => '22',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '97',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah 3 hari mengeluh demam, batuk, nyeri tenggorokan, pegal-pegal, pilek.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 120/80 mmHg; Nadi 95 x/menit; RR 22 x/menit; Suhu 38.5°C; SpO2 97%. Rinorea (+), faring hiperemis, ronkhi (-), wheezing (-).',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Istirahat, hidrasi cukup, antipiretik, vitamin, terapi simptomatik. Anjuran masker dan etika batuk.',
            'penilaian' => 'Influenza (ICD-10: J10/J11).',
            'instruksi' => 'Pantau suhu; bila sesak atau saturasi <94% segera ke IGD.',
            'evaluasi' => 'Kontrol 3-5 hari bila belum membaik atau muncul tanda bahaya.',
            'nip' => '19830112',
          ),
          61 => 
          array (
            'no_rawat' => '2025/12/01/000005',
            'tgl_perawatan' => '2025-12-01',
            'jam_rawat' => '22:44:00',
            'suhu_tubuh' => '36.8',
            'tensi' => '150/95',
            'nadi' => '85',
            'respirasi' => '18',
            'tinggi' => '165',
            'berat' => '70',
            'spo2' => '98',
            'gcs' => '15',
            'kesadaran' => 'Compos Mentis',
            'keluhan' => 'Pasien mengatakan sudah beberapa minggu mengeluh pusing/sakit kepala, kadang berdebar. Riwayat tekanan darah tinggi.',
            'pemeriksaan' => 'Keadaan umum baik, CM; TD 150/95 mmHg; Nadi 85 x/menit reguler; RR 18 x/menit; Suhu 36.8°C; SpO2 98%. Tidak ada distress napas, JVP normal, edema tungkai (-), bunyi jantung normal.',
            'alergi' => 'Tidak Ada',
            'lingkar_perut' => '72',
            'rtl' => 'Edukasi diet rendah garam, olahraga teratur, monitoring tekanan darah. Terapi antihipertensi sesuai resep dan kontrol berkala.',
            'penilaian' => 'Hipertensi esensial (ICD-10: I10).',
            'instruksi' => 'Pantau tekanan darah di rumah, hindari rokok/kafein.',
            'evaluasi' => 'Rencana kontrol 1-2 minggu untuk evaluasi TD dan gejala.',
            'nip' => '19830112',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}