<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PenilaianMedisRanapNeonatuTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_medis_ranap_neonatus')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_medis_ranap_neonatus')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/04/25/000001',
            'tanggal' => '2025-06-19 14:08:11',
            'kd_dokter' => 'D0000002',
            'no_rkm_medis_ibu' => '000010',
            'g' => '1',
            'p' => '2',
            'a' => '3',
            'hidup' => '1',
            'usiahamil' => '3',
            'hbsag' => 'Negatif (-)',
            'hiv' => 'Negatif (-)',
            'syphilis' => 'Negatif (-)',
            'riwayat_obstetri_ibu' => 'Tidak Ada',
            'keterangan_riwayat_obstetri_ibu' => '1',
            'faktor_risiko_neonatal' => 'Tidak Ada',
            'keterangan_faktor_risiko_neonatal' => '',
            'tanggal_persalinan' => '2025-06-19 14:08:11',
            'bersalin_di' => '',
            'inisiasi_menyusui' => 'Ya',
            'jenis_persalinan' => 'Spontan/Normal',
            'indikasi' => '',
            'aterm' => 'Ya',
            'bernafas' => 'Ya',
            'tanus_otot' => 'Ya',
            'cairan_amnion' => 'Ya',
            'f1' => '1',
            'u1' => '1',
            't1' => '1',
            'r1' => '1',
            'w1' => '1',
            'n1' => '5',
            'f5' => '1',
            'u5' => '1',
            't5' => '1',
            'r5' => '1',
            'w5' => '1',
            'n5' => '5',
            'f10' => '1',
            'u10' => '1',
            't10' => '1',
            'r10' => '1',
            'w10' => '1',
            'n10' => '5',
            'frekuensi_napas' => '< 60',
            'nilai_frekuensi_napas' => 0,
            'retraksi' => 'Tidak Ada',
            'nilai_retraksi' => 0,
            'sianosis' => 'Tidak Ada',
            'nilai_sianosis' => 0,
            'jalan_masuk_udara' => 'Baik',
            'nilai_jalan_masuk_udara' => 0,
            'grunting' => 'Tidak Ada',
            'nilai_grunting' => 0,
            'total_down_score' => 0,
            'keterangan_down_Score' => '',
            'nadi' => '',
            'rr' => '',
            'suhu' => '',
            'saturasi' => '',
            'bb' => '',
            'pb' => '',
            'lk' => '',
            'ld' => '',
            'keadaan_umum' => 'Normal',
            'keterangan_keadaan_umum' => '',
            'kulit' => 'Normal',
            'keterangan_kulit' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'mata' => 'Normal',
            'keterangan_mata' => '',
            'telinga' => 'Normal',
            'keterangan_telinga' => '',
            'hidung' => 'Normal',
            'keterangan_hidung' => '',
            'mulut' => 'Normal',
            'keterangan_mulut' => '',
            'tenggorokan' => 'Normal',
            'keterangan_tenggorokan' => '',
            'leher' => 'Normal',
            'keterangan_leher' => '',
            'thorax' => 'Normal',
            'keterangan_thorax' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'genitalia' => 'Normal',
            'keterangan_genitalia' => '',
            'anus' => 'Normal',
            'keterangan_anus' => '',
            'muskulos' => 'Normal',
            'keterangan_muskulos' => '',
            'ekstrimitas' => 'Normal',
            'keterangan_ekstrimitas' => '',
            'paru' => 'Normal',
            'keterangan_paru' => '',
            'refleks' => 'Normal',
            'keterangan_refleks' => '',
            'kelainan_lainnya' => '',
            'pemeriksaan_regional' => '1',
            'lab' => '1',
            'radiologi' => '1',
            'penunjanglainnya' => '1',
            'diagnosis' => '1',
            'tata' => '11',
            'edukasi' => '-',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}