<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PenilaianAwalKeperawatanRanapTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_awal_keperawatan_ranap')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_awal_keperawatan_ranap')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/06/28/000001',
            'tanggal' => '2025-06-28 09:37:38',
            'informasi' => 'Autoanamnesis',
            'ket_informasi' => '-',
            'tiba_diruang_rawat' => 'Jalan Tanpa Bantuan',
            'kasus_trauma' => 'Trauma',
            'cara_masuk' => 'Poli',
            'rps' => '-',
            'rpd' => '-',
            'rpk' => '-',
            'rpo' => '-',
            'riwayat_pembedahan' => '-',
            'riwayat_dirawat_dirs' => '-',
            'alat_bantu_dipakai' => 'Kacamata',
            'riwayat_kehamilan' => 'Tidak',
            'riwayat_kehamilan_perkiraan' => '-',
            'riwayat_tranfusi' => '-',
            'riwayat_alergi' => '',
            'riwayat_merokok' => 'Tidak',
            'riwayat_merokok_jumlah' => '',
            'riwayat_alkohol' => 'Tidak',
            'riwayat_alkohol_jumlah' => '',
            'riwayat_narkoba' => 'Tidak',
            'riwayat_olahraga' => 'Tidak',
            'pemeriksaan_mental' => '',
            'pemeriksaan_keadaan_umum' => 'Baik',
            'pemeriksaan_gcs' => '',
            'pemeriksaan_td' => '',
            'pemeriksaan_nadi' => '',
            'pemeriksaan_rr' => '',
            'pemeriksaan_suhu' => '',
            'pemeriksaan_spo2' => '',
            'pemeriksaan_bb' => '',
            'pemeriksaan_tb' => '',
            'pemeriksaan_susunan_kepala' => 'TAK',
            'pemeriksaan_susunan_kepala_keterangan' => '',
            'pemeriksaan_susunan_wajah' => 'TAK',
            'pemeriksaan_susunan_wajah_keterangan' => '',
            'pemeriksaan_susunan_leher' => 'TAK',
            'pemeriksaan_susunan_kejang' => 'TAK',
            'pemeriksaan_susunan_kejang_keterangan' => '',
            'pemeriksaan_susunan_sensorik' => 'TAK',
            'pemeriksaan_kardiovaskuler_denyut_nadi' => 'Teratur',
            'pemeriksaan_kardiovaskuler_sirkulasi' => 'Akral Hangat',
            'pemeriksaan_kardiovaskuler_sirkulasi_keterangan' => '',
            'pemeriksaan_kardiovaskuler_pulsasi' => 'Kuat',
            'pemeriksaan_respirasi_pola_nafas' => 'Normal',
            'pemeriksaan_respirasi_retraksi' => 'Tidak Ada',
            'pemeriksaan_respirasi_suara_nafas' => 'Vesikuler',
            'pemeriksaan_respirasi_volume_pernafasan' => 'Normal',
            'pemeriksaan_respirasi_jenis_pernafasan' => 'Pernafasan Dada',
            'pemeriksaan_respirasi_jenis_pernafasan_keterangan' => '',
            'pemeriksaan_respirasi_irama_nafas' => 'Teratur',
            'pemeriksaan_respirasi_batuk' => 'Tidak',
            'pemeriksaan_gastrointestinal_mulut' => 'TAK',
            'pemeriksaan_gastrointestinal_mulut_keterangan' => '',
            'pemeriksaan_gastrointestinal_gigi' => 'TAK',
            'pemeriksaan_gastrointestinal_gigi_keterangan' => '',
            'pemeriksaan_gastrointestinal_lidah' => 'TAK',
            'pemeriksaan_gastrointestinal_lidah_keterangan' => '',
            'pemeriksaan_gastrointestinal_tenggorokan' => 'TAK',
            'pemeriksaan_gastrointestinal_tenggorokan_keterangan' => '',
            'pemeriksaan_gastrointestinal_abdomen' => 'Supel',
            'pemeriksaan_gastrointestinal_abdomen_keterangan' => '',
            'pemeriksaan_gastrointestinal_peistatik_usus' => 'TAK',
            'pemeriksaan_gastrointestinal_anus' => 'TAK',
            'pemeriksaan_neurologi_pengelihatan' => 'TAK',
            'pemeriksaan_neurologi_pengelihatan_keterangan' => '',
            'pemeriksaan_neurologi_alat_bantu_penglihatan' => 'Tidak',
            'pemeriksaan_neurologi_pendengaran' => 'TAK',
            'pemeriksaan_neurologi_bicara' => 'Jelas',
            'pemeriksaan_neurologi_bicara_keterangan' => '',
            'pemeriksaan_neurologi_sensorik' => 'TAK',
            'pemeriksaan_neurologi_motorik' => 'TAK',
            'pemeriksaan_neurologi_kekuatan_otot' => 'Kuat',
            'pemeriksaan_integument_warnakulit' => 'Normal',
            'pemeriksaan_integument_turgor' => 'Baik',
            'pemeriksaan_integument_kulit' => 'Normal',
            'pemeriksaan_integument_dekubitas' => 'Tidak Ada',
            'pemeriksaan_muskuloskletal_pergerakan_sendi' => 'Bebas',
            'pemeriksaan_muskuloskletal_kekauatan_otot' => 'Baik',
            'pemeriksaan_muskuloskletal_nyeri_sendi' => 'Tidak Ada',
            'pemeriksaan_muskuloskletal_nyeri_sendi_keterangan' => '',
            'pemeriksaan_muskuloskletal_oedema' => 'Tidak Ada',
            'pemeriksaan_muskuloskletal_oedema_keterangan' => '',
            'pemeriksaan_muskuloskletal_fraktur' => 'Tidak Ada',
            'pemeriksaan_muskuloskletal_fraktur_keterangan' => '',
            'pemeriksaan_eliminasi_bab_frekuensi_jumlah' => '',
            'pemeriksaan_eliminasi_bab_frekuensi_durasi' => '',
            'pemeriksaan_eliminasi_bab_konsistensi' => '',
            'pemeriksaan_eliminasi_bab_warna' => '',
            'pemeriksaan_eliminasi_bak_frekuensi_jumlah' => '',
            'pemeriksaan_eliminasi_bak_frekuensi_durasi' => '',
            'pemeriksaan_eliminasi_bak_warna' => '',
            'pemeriksaan_eliminasi_bak_lainlain' => '',
            'pola_aktifitas_makanminum' => 'Mandiri',
            'pola_aktifitas_mandi' => 'Mandiri',
            'pola_aktifitas_eliminasi' => 'Mandiri',
            'pola_aktifitas_berpakaian' => 'Mandiri',
            'pola_aktifitas_berpindah' => 'Mandiri',
            'pola_nutrisi_frekuesi_makan' => '',
            'pola_nutrisi_jenis_makanan' => '',
            'pola_nutrisi_porsi_makan' => '',
            'pola_tidur_lama_tidur' => '',
            'pola_tidur_gangguan' => 'Tidak Ada Gangguan',
            'pengkajian_fungsi_kemampuan_sehari' => 'Mandiri',
            'pengkajian_fungsi_aktifitas' => 'Tirah Baring',
            'pengkajian_fungsi_berjalan' => 'TAK',
            'pengkajian_fungsi_berjalan_keterangan' => '',
            'pengkajian_fungsi_ambulasi' => 'Walker',
            'pengkajian_fungsi_ekstrimitas_atas' => 'TAK',
            'pengkajian_fungsi_ekstrimitas_atas_keterangan' => '',
            'pengkajian_fungsi_ekstrimitas_bawah' => 'TAK',
            'pengkajian_fungsi_ekstrimitas_bawah_keterangan' => '',
            'pengkajian_fungsi_menggenggam' => 'Tidak Ada Kesulitan',
            'pengkajian_fungsi_menggenggam_keterangan' => '',
            'pengkajian_fungsi_koordinasi' => 'Tidak Ada Kesulitan',
            'pengkajian_fungsi_koordinasi_keterangan' => '',
            'pengkajian_fungsi_kesimpulan' => 'Tidak (Tidak Perlu Co DPJP)',
            'riwayat_psiko_kondisi_psiko' => 'Tidak Ada Masalah',
            'riwayat_psiko_gangguan_jiwa' => 'Tidak',
            'riwayat_psiko_perilaku' => 'Tidak Ada Masalah',
            'riwayat_psiko_perilaku_keterangan' => '',
            'riwayat_psiko_hubungan_keluarga' => 'Harmonis',
            'riwayat_psiko_tinggal' => 'Sendiri',
            'riwayat_psiko_tinggal_keterangan' => '',
            'riwayat_psiko_nilai_kepercayaan' => 'Tidak Ada',
            'riwayat_psiko_nilai_kepercayaan_keterangan' => '',
            'riwayat_psiko_pendidikan_pj' => '-',
            'riwayat_psiko_edukasi_diberikan' => 'Pasien',
            'riwayat_psiko_edukasi_diberikan_keterangan' => '',
            'penilaian_nyeri' => 'Tidak Ada Nyeri',
            'penilaian_nyeri_penyebab' => 'Proses Penyakit',
            'penilaian_nyeri_ket_penyebab' => '',
            'penilaian_nyeri_kualitas' => 'Seperti Tertusuk',
            'penilaian_nyeri_ket_kualitas' => '',
            'penilaian_nyeri_lokasi' => '',
            'penilaian_nyeri_menyebar' => 'Tidak',
            'penilaian_nyeri_skala' => '0',
            'penilaian_nyeri_waktu' => '',
            'penilaian_nyeri_hilang' => 'Istirahat',
            'penilaian_nyeri_ket_hilang' => '',
            'penilaian_nyeri_diberitahukan_dokter' => 'Tidak',
            'penilaian_nyeri_jam_diberitahukan_dokter' => '',
            'penilaian_jatuhmorse_skala1' => 'Tidak',
            'penilaian_jatuhmorse_nilai1' => 0,
            'penilaian_jatuhmorse_skala2' => 'Tidak',
            'penilaian_jatuhmorse_nilai2' => 0,
            'penilaian_jatuhmorse_skala3' => 'Tidak Ada/Kursi Roda/Perawat/Tirah Baring',
            'penilaian_jatuhmorse_nilai3' => 0,
            'penilaian_jatuhmorse_skala4' => 'Tidak',
            'penilaian_jatuhmorse_nilai4' => 0,
            'penilaian_jatuhmorse_skala5' => 'Normal/Tirah Baring/Imobilisasi',
            'penilaian_jatuhmorse_nilai5' => 0,
            'penilaian_jatuhmorse_skala6' => 'Sadar Akan Kemampuan Diri Sendiri',
            'penilaian_jatuhmorse_nilai6' => 0,
            'penilaian_jatuhmorse_totalnilai' => 0,
            'penilaian_jatuhsydney_skala1' => 'Tidak',
            'penilaian_jatuhsydney_nilai1' => 0,
            'penilaian_jatuhsydney_skala2' => 'Tidak',
            'penilaian_jatuhsydney_nilai2' => 0,
            'penilaian_jatuhsydney_skala3' => 'Tidak',
            'penilaian_jatuhsydney_nilai3' => 0,
            'penilaian_jatuhsydney_skala4' => 'Tidak',
            'penilaian_jatuhsydney_nilai4' => 0,
            'penilaian_jatuhsydney_skala5' => 'Tidak',
            'penilaian_jatuhsydney_nilai5' => 0,
            'penilaian_jatuhsydney_skala6' => 'Tidak',
            'penilaian_jatuhsydney_nilai6' => 0,
            'penilaian_jatuhsydney_skala7' => 'Tidak',
            'penilaian_jatuhsydney_nilai7' => 0,
            'penilaian_jatuhsydney_skala8' => 'Tidak',
            'penilaian_jatuhsydney_nilai8' => 0,
            'penilaian_jatuhsydney_skala9' => 'Tidak',
            'penilaian_jatuhsydney_nilai9' => 0,
            'penilaian_jatuhsydney_skala10' => 'Tidak',
            'penilaian_jatuhsydney_nilai10' => 0,
            'penilaian_jatuhsydney_skala11' => 'Tidak',
            'penilaian_jatuhsydney_nilai11' => 0,
            'penilaian_jatuhsydney_totalnilai' => 0,
            'skrining_gizi1' => 'Tidak ada penurunan berat badan',
            'nilai_gizi1' => 0,
            'skrining_gizi2' => 'Tidak',
            'nilai_gizi2' => 0,
            'nilai_total_gizi' => 0.0,
            'skrining_gizi_diagnosa_khusus' => 'Tidak',
            'skrining_gizi_ket_diagnosa_khusus' => '',
            'skrining_gizi_diketahui_dietisen' => 'Tidak',
            'skrining_gizi_jam_diketahui_dietisen' => '',
            'rencana' => '',
            'nip1' => '123124',
            'nip2' => '156798',
            'kd_dokter' => 'D0000004',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}