<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PenilaianAwalKeperawatanKebidananTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_awal_keperawatan_kebidanan')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_awal_keperawatan_kebidanan')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/06/23/000001',
            'tanggal' => '2025-06-23 11:30:34',
            'informasi' => 'Autoanamnesis',
            'td' => '-',
            'nadi' => '0',
            'rr' => '0',
            'suhu' => '-',
            'gcs' => '-',
            'bb' => '-',
            'tb' => '-',
            'lila' => '-',
            'bmi' => '-',
            'tfu' => '',
            'tbj' => '',
            'letak' => '',
            'presentasi' => '',
            'penurunan' => '',
            'his' => '',
            'kekuatan' => '',
            'lamanya' => '',
            'bjj' => '',
            'ket_bjj' => 'Teratur',
            'portio' => '',
            'serviks' => '',
            'ketuban' => '',
            'hodge' => '',
            'inspekulo' => 'Dilakukan',
            'ket_inspekulo' => '',
            'ctg' => 'Dilakukan',
            'ket_ctg' => '',
            'usg' => 'Dilakukan',
            'ket_usg' => '',
            'lab' => 'Dilakukan',
            'ket_lab' => '',
            'lakmus' => 'Dilakukan',
            'ket_lakmus' => '',
            'panggul' => 'Luas',
            'keluhan_utama' => '-',
            'umur' => '',
            'lama' => '',
            'banyaknya' => '',
            'haid' => '',
            'siklus' => '',
            'ket_siklus' => 'Teratur',
            'ket_siklus1' => 'Tidak Ada Masalah',
            'status' => 'Menikah',
            'kali' => '',
            'usia1' => '',
            'ket1' => '-',
            'usia2' => '',
            'ket2' => '-',
            'usia3' => '',
            'ket3' => '-',
            'hpht' => '2025-06-23',
            'usia_kehamilan' => '',
            'tp' => '2025-06-23',
            'imunisasi' => 'Tidak',
            'ket_imunisasi' => '',
            'g' => '',
            'p' => '',
            'a' => '',
            'hidup' => '',
            'ginekologi' => 'Tidak Ada',
            'kebiasaan' => '-',
            'ket_kebiasaan' => '',
            'kebiasaan1' => 'Tidak',
            'ket_kebiasaan1' => '',
            'kebiasaan2' => 'Tidak',
            'ket_kebiasaan2' => '',
            'kebiasaan3' => 'Tidak',
            'kb' => 'Belum Pernah',
            'ket_kb' => '',
            'komplikasi' => 'Tidak Ada',
            'ket_komplikasi' => '',
            'berhenti' => '',
            'alasan' => '',
            'alat_bantu' => 'Tidak',
            'ket_bantu' => '',
            'prothesa' => 'Tidak',
            'ket_pro' => '',
            'adl' => 'Mandiri',
            'status_psiko' => 'Tenang',
            'ket_psiko' => '',
            'hub_keluarga' => 'Baik',
            'tinggal_dengan' => 'Sendiri',
            'ket_tinggal' => '',
            'ekonomi' => 'Baik',
            'budaya' => 'Tidak Ada',
            'ket_budaya' => '',
            'edukasi' => 'Pasien',
            'ket_edukasi' => '',
            'berjalan_a' => 'Tidak',
            'berjalan_b' => 'Tidak',
            'berjalan_c' => 'Tidak',
            'hasil' => 'Tidak Beresiko (Tidak Ditemukan A Dan B)',
            'lapor' => 'Tidak',
            'ket_lapor' => '',
            'sg1' => 'Ya, 6-10 Kg',
            'nilai1' => '2',
            'sg2' => 'Ya',
            'nilai2' => '1',
            'total_hasil' => '3',
            'nyeri' => 'Tidak Ada Nyeri',
            'provokes' => 'Proses Penyakit',
            'ket_provokes' => '',
            'quality' => 'Seperti Tertusuk',
            'ket_quality' => '',
            'lokasi' => '',
            'menyebar' => 'Tidak',
            'skala_nyeri' => '0',
            'durasi' => '',
            'nyeri_hilang' => 'Istirahat',
            'ket_nyeri' => '',
            'pada_dokter' => 'Tidak',
            'ket_dokter' => '',
            'masalah' => 'tes',
            'tindakan' => 'tes',
            'nip' => '123124',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}