<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PenilaianMcuTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_mcu')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_mcu')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/05/15/000001',
            'tanggal' => '2025-05-09 13:42:22',
            'kd_dokter' => 'D0000004',
            'informasi' => 'Autoanamnesis',
            'rps' => '1',
            'rpk' => '2',
            'rpd' => '3',
            'alergi' => '4',
            'keadaan' => 'Tidak Baik',
            'kesadaran' => 'Composmentis',
            'td' => '5',
            'nadi' => '6',
            'rr' => '7',
            'tb' => '8',
            'bb' => '9',
            'suhu' => '10',
            'bmi' => '1406.3',
            'kasifikasi_bmi' => 'Obesitas II',
            'lingkar_pinggang' => '11',
            'risiko_lingkar_pinggang' => 'Berat',
            'submandibula' => 'Tidak Membesar',
            'axilla' => 'Tidak Membesar',
            'supraklavikula' => 'Tidak Membesar',
            'leher' => 'Tidak Membesar',
            'inguinal' => 'Tidak Membesar',
            'oedema' => 'Tidak Ada',
            'sinus_frontalis' => 'Tidak Ada',
            'sinus_maxilaris' => 'Tidak Ada',
            'rambut' => '12',
            'palpebra' => 'Normal',
            'sklera' => 'Normal',
            'cornea' => 'Tidak Normal',
            'buta_warna' => 'Buta Warna Partial',
            'konjungtiva' => 'Hiperemis',
            'lensa' => 'Kacamata',
            'pupil' => 'Anisokor',
            'menggunakan_kacamata' => 'Tidak',
            'visus' => '13',
            'luas_lapang_pandang' => 'Tidak Normal',
            'keterangan_luas_lapang_pandang' => '14',
            'lubang_telinga' => 'Serumen Prop',
            'daun_telinga' => 'Tidak Normal',
            'selaput_pendengaran' => 'Tidak Intak',
            'proc_mastoideus' => 'Tidak Normal',
            'septum_nasi' => 'Deviasi',
            'lubang_hidung' => 'Epistaksis',
            'sinus' => 'Tidak Normal',
            'bibir' => 'Lembab',
            'gusi' => 'Tidak Normal',
            'gigi' => 'Tidak Normal',
            'caries' => 'Tidak Ada',
            'lidah' => 'Tremor',
            'faring' => 'Hiperemis',
            'tonsil' => 'T4-T4',
            'kelenjar_limfe' => 'Tidak Membesar',
            'kelenjar_gondok' => 'Tidak Membesar',
            'gerakan_dada' => 'Tidak Simetris',
            'vocal_femitus' => 'Tidak Sama',
            'perkusi_dada' => 'Sonor',
            'bunyi_napas' => 'Bronkhial',
            'bunyi_tambahan' => 'Wheezing',
            'ictus_cordis' => 'Tidak Terlihat',
            'bunyi_jantung' => 'Reguler',
            'batas' => 'Melebar',
            'mamae' => 'Tidak Normal',
            'keterangan_mamae' => '15',
            'inspeksi' => 'Cembung',
            'palpasi' => 'Nyeri Tekan Right Lower Quadrant',
            'hepar' => 'Tidak Membesar',
            'perkusi_abdomen' => 'Hipertimpani',
            'auskultasi' => 'Bising Usus Meningkat',
            'limpa' => 'Tidak Membesar',
            'costovertebral' => 'Ada Di Kanan',
            'scoliosis' => 'Tidak Ada',
            'kondisi_kulit' => 'Penyakit Kulit',
            'penyakit_kulit' => '16',
            'ekstrimitas_atas' => 'Tidak Normal',
            'ekstrimitas_atas_ket' => '17',
            'ekstrimitas_bawah' => 'Tidak Normal',
            'ekstrimitas_bawah_ket' => '18',
            'area_genitalia' => 'Tidak Ada Kelainan',
            'keterangan_area_genitalia' => '19
        12121',
            'anus_perianal' => 'Normal',
            'keterangan_anus_perianal' => '20
        12122',
            'laborat' => '21',
            'radiologi' => '22',
            'ekg' => '23',
            'spirometri' => '24',
            'audiometri' => '25',
            'treadmill' => '26',
            'romberg_test' => '27',
            'back_strength' => '28',
            'abi_tangan_kanan' => '29',
            'abi_tangan_kiri' => '30',
            'abi_kaki_kanan' => '31',
            'abi_kaki_kiri' => '32',
            'lainlain' => '34',
            'merokok' => '35 s a sa s a sa s as a sa s a sa s a sa s as a s as a sa s as
         a sa s a sa ',
            'alkohol' => '36 s a s as as a s as as a s as a sa s as a sa s as a sa s a sa s as
         a sa s as a sa s as ',
            'kesimpulan' => '37',
            'anjuran' => '38 
        asas
        asas
        sas
        ok',
          ),
          1 => 
          array (
            'no_rawat' => '2025/05/26/000002',
            'tanggal' => '2025-05-26 14:20:26',
            'kd_dokter' => 'D0000004',
            'informasi' => 'Autoanamnesis',
            'rps' => '212',
            'rpk' => '1212',
            'rpd' => '1212',
            'alergi' => '',
            'keadaan' => 'Baik',
            'kesadaran' => 'Composmentis',
            'td' => '',
            'nadi' => '',
            'rr' => '',
            'tb' => '120',
            'bb' => '130',
            'suhu' => '',
            'bmi' => '90.3',
            'kasifikasi_bmi' => 'Obesitas II',
            'lingkar_pinggang' => '40',
            'risiko_lingkar_pinggang' => 'Berat',
            'submandibula' => 'Tidak Membesar',
            'axilla' => 'Tidak Membesar',
            'supraklavikula' => 'Tidak Membesar',
            'leher' => 'Tidak Membesar',
            'inguinal' => 'Tidak Membesar',
            'oedema' => 'Tidak Ada',
            'sinus_frontalis' => 'Tidak Ada',
            'sinus_maxilaris' => 'Tidak Ada',
            'rambut' => '',
            'palpebra' => 'Normal',
            'sklera' => 'Normal',
            'cornea' => 'Normal',
            'buta_warna' => 'Normal',
            'konjungtiva' => 'Normal',
            'lensa' => 'Jernih',
            'pupil' => 'Isokor',
            'menggunakan_kacamata' => 'Tidak',
            'visus' => '',
            'luas_lapang_pandang' => 'Normal',
            'keterangan_luas_lapang_pandang' => '',
            'lubang_telinga' => 'Normal',
            'daun_telinga' => 'Normal',
            'selaput_pendengaran' => 'Intak',
            'proc_mastoideus' => 'Normal',
            'septum_nasi' => 'Normal',
            'lubang_hidung' => 'Lapang',
            'sinus' => 'Normal',
            'bibir' => 'Lembab',
            'gusi' => 'Normal',
            'gigi' => 'Normal',
            'caries' => 'Tidak Ada',
            'lidah' => 'Bersih',
            'faring' => 'Normal',
            'tonsil' => 'T1-T1',
            'kelenjar_limfe' => 'Tidak Membesar',
            'kelenjar_gondok' => 'Tidak Membesar',
            'gerakan_dada' => 'Simetris',
            'vocal_femitus' => 'Sama',
            'perkusi_dada' => 'Sonor',
            'bunyi_napas' => 'Vesikuler',
            'bunyi_tambahan' => 'Tidak Ada',
            'ictus_cordis' => 'Tidak Terlihat',
            'bunyi_jantung' => 'Reguler',
            'batas' => 'Normal',
            'mamae' => 'Normal',
            'keterangan_mamae' => '',
            'inspeksi' => 'Datar',
            'palpasi' => 'Supel',
            'hepar' => 'Tidak Membesar',
            'perkusi_abdomen' => 'Timpani',
            'auskultasi' => 'Normal',
            'limpa' => 'Tidak Membesar',
            'costovertebral' => 'Tidak Ada',
            'scoliosis' => 'Tidak Ada',
            'kondisi_kulit' => 'Normal',
            'penyakit_kulit' => '',
            'ekstrimitas_atas' => 'Normal',
            'ekstrimitas_atas_ket' => '',
            'ekstrimitas_bawah' => 'Normal',
            'ekstrimitas_bawah_ket' => '',
            'area_genitalia' => 'Tidak Ada Kelainan',
            'keterangan_area_genitalia' => '',
            'anus_perianal' => 'Normal',
            'keterangan_anus_perianal' => '',
            'laborat' => '',
            'radiologi' => '',
            'ekg' => '',
            'spirometri' => '',
            'audiometri' => '',
            'treadmill' => '',
            'romberg_test' => '',
            'back_strength' => '',
            'abi_tangan_kanan' => '',
            'abi_tangan_kiri' => '',
            'abi_kaki_kanan' => '',
            'abi_kaki_kiri' => '',
            'lainlain' => '',
            'merokok' => '',
            'alkohol' => '',
            'kesimpulan' => '12',
            'anjuran' => '12122',
          ),
          2 => 
          array (
            'no_rawat' => '2025/06/23/000001',
            'tanggal' => '2025-06-23 13:13:25',
            'kd_dokter' => 'D0000004',
            'informasi' => 'Autoanamnesis',
            'rps' => '1',
            'rpk' => '2',
            'rpd' => '3',
            'alergi' => '-',
            'keadaan' => 'Baik',
            'kesadaran' => 'Composmentis',
            'td' => '',
            'nadi' => '',
            'rr' => '10',
            'tb' => '10',
            'bb' => '10',
            'suhu' => '10',
            'bmi' => '1000.0',
            'kasifikasi_bmi' => 'Obesitas II',
            'lingkar_pinggang' => '90',
            'risiko_lingkar_pinggang' => 'Sangat',
            'submandibula' => 'Tidak Membesar',
            'axilla' => 'Tidak Membesar',
            'supraklavikula' => 'Tidak Membesar',
            'leher' => 'Tidak Membesar',
            'inguinal' => 'Tidak Membesar',
            'oedema' => 'Tidak Ada',
            'sinus_frontalis' => 'Tidak Ada',
            'sinus_maxilaris' => 'Tidak Ada',
            'rambut' => '',
            'palpebra' => 'Normal',
            'sklera' => 'Normal',
            'cornea' => 'Normal',
            'buta_warna' => 'Normal',
            'konjungtiva' => 'Normal',
            'lensa' => 'Jernih',
            'pupil' => 'Isokor',
            'menggunakan_kacamata' => 'Tidak',
            'visus' => '',
            'luas_lapang_pandang' => 'Normal',
            'keterangan_luas_lapang_pandang' => '',
            'lubang_telinga' => 'Normal',
            'daun_telinga' => 'Normal',
            'selaput_pendengaran' => 'Intak',
            'proc_mastoideus' => 'Normal',
            'septum_nasi' => 'Normal',
            'lubang_hidung' => 'Lapang',
            'sinus' => 'Normal',
            'bibir' => 'Lembab',
            'gusi' => 'Normal',
            'gigi' => 'Normal',
            'caries' => 'Tidak Ada',
            'lidah' => 'Bersih',
            'faring' => 'Normal',
            'tonsil' => 'T1-T1',
            'kelenjar_limfe' => 'Tidak Membesar',
            'kelenjar_gondok' => 'Tidak Membesar',
            'gerakan_dada' => 'Simetris',
            'vocal_femitus' => 'Sama',
            'perkusi_dada' => 'Sonor',
            'bunyi_napas' => 'Vesikuler',
            'bunyi_tambahan' => 'Tidak Ada',
            'ictus_cordis' => 'Tidak Terlihat',
            'bunyi_jantung' => 'Reguler',
            'batas' => 'Normal',
            'mamae' => 'Normal',
            'keterangan_mamae' => '',
            'inspeksi' => 'Datar',
            'palpasi' => 'Supel',
            'hepar' => 'Tidak Membesar',
            'perkusi_abdomen' => 'Timpani',
            'auskultasi' => 'Normal',
            'limpa' => 'Tidak Membesar',
            'costovertebral' => 'Tidak Ada',
            'scoliosis' => 'Tidak Ada',
            'kondisi_kulit' => 'Normal',
            'penyakit_kulit' => '',
            'ekstrimitas_atas' => 'Normal',
            'ekstrimitas_atas_ket' => '',
            'ekstrimitas_bawah' => 'Normal',
            'ekstrimitas_bawah_ket' => '',
            'area_genitalia' => 'Tidak Ada Kelainan',
            'keterangan_area_genitalia' => '',
            'anus_perianal' => 'Normal',
            'keterangan_anus_perianal' => '',
            'laborat' => '-',
            'radiologi' => '=',
            'ekg' => '=',
            'spirometri' => '',
            'audiometri' => '',
            'treadmill' => '',
            'romberg_test' => '',
            'back_strength' => '',
            'abi_tangan_kanan' => '',
            'abi_tangan_kiri' => '',
            'abi_kaki_kanan' => '',
            'abi_kaki_kiri' => '',
            'lainlain' => '',
            'merokok' => '',
            'alkohol' => '',
            'kesimpulan' => '-',
            'anjuran' => 'tes',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}