<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PenilaianMedisRalanPenyakitDalamTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_medis_ralan_penyakit_dalam')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('penilaian_medis_ralan_penyakit_dalam')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/04/27/000001',
            'tanggal' => '2025-04-27 08:36:21',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => '1212',
            'rps' => '21212',
            'rpd' => '1212',
            'rpo' => '1212',
            'alergi' => '1212',
            'kondisi' => '1212',
            'status' => '21212',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '1212',
            'lab' => '21212',
            'rad' => '1212',
            'penunjanglain' => '21212',
            'diagnosis' => '121212',
            'diagnosis2' => '212',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '',
          ),
          1 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'tanggal' => '2025-06-20 13:53:51',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => '-',
            'rps' => '-',
            'rpd' => '-',
            'rpo' => '-',
            'alergi' => '-',
            'kondisi' => '',
            'status' => '',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '-',
          ),
          2 => 
          array (
            'no_rawat' => '2025/06/30/000003',
            'tanggal' => '2025-06-30 09:16:43',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '-',
            'keluhan_utama' => 'Q',
            'rps' => 'Q',
            'rpd' => 'Q',
            'rpo' => 'Q',
            'alergi' => 'Q',
            'kondisi' => 'Q',
            'status' => 'Q',
            'td' => 'Q',
            'nadi' => 'Q',
            'suhu' => 'Q',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '-',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '-',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '',
          ),
          3 => 
          array (
            'no_rawat' => '2025/07/29/000001',
            'tanggal' => '2025-07-29 09:28:23',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => '121212',
            'rps' => '21212',
            'rpd' => '1212',
            'rpo' => '1212',
            'alergi' => '1212',
            'kondisi' => '1212',
            'status' => '212',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '12',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '12',
          ),
          4 => 
          array (
            'no_rawat' => '2025/08/11/000001',
            'tanggal' => '2025-08-11 14:22:17',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => '-',
            'rps' => '-',
            'rpd' => '-',
            'rpo' => '-',
            'alergi' => '',
            'kondisi' => '-',
            'status' => '',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '-',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '',
          ),
          5 => 
          array (
            'no_rawat' => '2025/08/19/000001',
            'tanggal' => '2025-08-19 10:07:48',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => '-',
            'rps' => '-',
            'rpd' => '-',
            'rpo' => '-',
            'alergi' => '-',
            'kondisi' => '',
            'status' => '-',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '',
          ),
          6 => 
          array (
            'no_rawat' => '2025/08/21/000001',
            'tanggal' => '2025-08-21 14:45:33',
            'kd_dokter' => 'D0000004',
            'anamnesis' => 'Autoanamnesis',
            'hubungan' => '',
            'keluhan_utama' => 'wqwqw',
            'rps' => 'wqwqw',
            'rpd' => 'qwqw',
            'rpo' => 'wqw',
            'alergi' => 'wqw',
            'kondisi' => '',
            'status' => '',
            'td' => '',
            'nadi' => '',
            'suhu' => '',
            'rr' => '',
            'bb' => '',
            'nyeri' => '',
            'gcs' => '',
            'kepala' => 'Normal',
            'keterangan_kepala' => '',
            'thoraks' => 'Normal',
            'keterangan_thorak' => '',
            'abdomen' => 'Normal',
            'keterangan_abdomen' => '',
            'ekstremitas' => 'Normal',
            'keterangan_ekstremitas' => '',
            'lainnya' => '',
            'lab' => '',
            'rad' => '',
            'penunjanglain' => '',
            'diagnosis' => '',
            'diagnosis2' => '',
            'permasalahan' => '',
            'terapi' => '',
            'tindakan' => '',
            'edukasi' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}