<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PeriksaRadiologiTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('periksa_radiologi')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('periksa_radiologi')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/04/25/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU-01',
            'tgl_periksa' => '2025-06-11',
            'jam' => '19:20:31',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 98000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 180000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ranap',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          1 => 
          array (
            'no_rawat' => '2025/04/27/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'IG.AS-K1',
            'tgl_periksa' => '2025-04-27',
            'jam' => '08:48:08',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 141750.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 6250.0,
            'tarif_tindakan_dokter' => 55000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 210000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          2 => 
          array (
            'no_rawat' => '2025/05/26/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-05-26',
            'jam' => '10:51:25',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '9',
            'kV' => '8',
            'mAS' => '9',
            'FFD' => '9',
            'BSF' => '0',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          3 => 
          array (
            'no_rawat' => '2025/06/03/000002',
            'nip' => '123124',
            'kd_jenis_prw' => 'IG.AS- 1',
            'tgl_periksa' => '2025-06-03',
            'jam' => '08:55:16',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 147500.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 2500.0,
            'tarif_tindakan_dokter' => 55000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 210000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          4 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU-01',
            'tgl_periksa' => '2025-08-05',
            'jam' => '13:38:16',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 98000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 180000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ranap',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          5 => 
          array (
            'no_rawat' => '2025/06/25/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'ICU-01',
            'tgl_periksa' => '2025-06-25',
            'jam' => '09:02:18',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 98000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 180000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          6 => 
          array (
            'no_rawat' => '2025/06/30/000003',
            'nip' => '123124',
            'kd_jenis_prw' => 'IG.AS- 1',
            'tgl_periksa' => '2025-06-30',
            'jam' => '09:56:57',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 147500.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 2500.0,
            'tarif_tindakan_dokter' => 55000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 210000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          7 => 
          array (
            'no_rawat' => '2025/07/04/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'ICU-01',
            'tgl_periksa' => '2025-07-04',
            'jam' => '09:46:38',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 98000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 180000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          8 => 
          array (
            'no_rawat' => '2025/07/29/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-07-29',
            'jam' => '09:45:48',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          9 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-08-04',
            'jam' => '10:31:51',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          10 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'IG.AS- 1',
            'tgl_periksa' => '2025-08-04',
            'jam' => '10:39:56',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 147500.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 2500.0,
            'tarif_tindakan_dokter' => 55000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 210000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          11 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'IG.AS.RJ 4',
            'tgl_periksa' => '2025-08-04',
            'jam' => '10:39:56',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 276250.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 3750.0,
            'tarif_tindakan_dokter' => 190000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 475000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          12 => 
          array (
            'no_rawat' => '2025/08/04/000001',
            'nip' => '12/09/1988/001',
            'kd_jenis_prw' => 'IG.AS.RJ 5',
            'tgl_periksa' => '2025-08-04',
            'jam' => '10:39:56',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 276250.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 3750.0,
            'tarif_tindakan_dokter' => 190000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 475000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          13 => 
          array (
            'no_rawat' => '2025/08/11/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-08-11',
            'jam' => '14:29:20',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          14 => 
          array (
            'no_rawat' => '2025/08/19/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'IG.AS- 1',
            'tgl_periksa' => '2025-08-19',
            'jam' => '11:11:22',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 147500.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 2500.0,
            'tarif_tindakan_dokter' => 55000.0,
            'tarif_tindakan_petugas' => 5000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 210000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          15 => 
          array (
            'no_rawat' => '2025/08/21/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-08-21',
            'jam' => '14:55:50',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
          16 => 
          array (
            'no_rawat' => '2025/08/25/000001',
            'nip' => '123124',
            'kd_jenis_prw' => 'ICU.CTO-01',
            'tgl_periksa' => '2025-08-25',
            'jam' => '14:10:21',
            'dokter_perujuk' => 'D0000004',
            'bagian_rs' => 143000.0,
            'bhp' => 0.0,
            'tarif_perujuk' => 30000.0,
            'tarif_tindakan_dokter' => 45000.0,
            'tarif_tindakan_petugas' => 7000.0,
            'kso' => 0.0,
            'menejemen' => 0.0,
            'biaya' => 225000.0,
            'kd_dokter' => 'D0000004',
            'status' => 'Ralan',
            'proyeksi' => '',
            'kV' => '',
            'mAS' => '',
            'FFD' => '',
            'BSF' => '',
            'inak' => '',
            'jml_penyinaran' => '',
            'dosis' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}