<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PotonganTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('potongan')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('potongan')->insert(array (
          0 => 
          array (
            'tahun' => '2021',
            'bulan' => 8,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 210000.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 2000000.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          1 => 
          array (
            'tahun' => '2021',
            'bulan' => 8,
            'id' => 114,
            'bpjs' => 0.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          2 => 
          array (
            'tahun' => '2022',
            'bulan' => 1,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 210000.0,
            'angla' => 0.0,
            'telpri' => 300000.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          3 => 
          array (
            'tahun' => '2022',
            'bulan' => 1,
            'id' => 114,
            'bpjs' => 0.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          4 => 
          array (
            'tahun' => '2022',
            'bulan' => 3,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 2000.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          5 => 
          array (
            'tahun' => '2022',
            'bulan' => 8,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          6 => 
          array (
            'tahun' => '2022',
            'bulan' => 8,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 10000.0,
            'angkop' => 1050000.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          7 => 
          array (
            'tahun' => '2022',
            'bulan' => 11,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          8 => 
          array (
            'tahun' => '2022',
            'bulan' => 11,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 10000.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          9 => 
          array (
            'tahun' => '2023',
            'bulan' => 1,
            'id' => 112,
            'bpjs' => 0.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          10 => 
          array (
            'tahun' => '2023',
            'bulan' => 1,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 10000.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          11 => 
          array (
            'tahun' => '2023',
            'bulan' => 1,
            'id' => 116,
            'bpjs' => 50000.0,
            'jamsostek' => 0.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 50000.0,
            'ktg' => 'tes',
          ),
          12 => 
          array (
            'tahun' => '2024',
            'bulan' => 9,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 100000.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          13 => 
          array (
            'tahun' => '2024',
            'bulan' => 9,
            'id' => 116,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 100000.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 200000.0,
            'ktg' => 'tes',
          ),
          14 => 
          array (
            'tahun' => '2024',
            'bulan' => 10,
            'id' => 116,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          15 => 
          array (
            'tahun' => '2024',
            'bulan' => 10,
            'id' => 118,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          16 => 
          array (
            'tahun' => '2024',
            'bulan' => 11,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
          17 => 
          array (
            'tahun' => '2025',
            'bulan' => 5,
            'id' => 114,
            'bpjs' => 50000.0,
            'jamsostek' => 22540.0,
            'dansos' => 2000.0,
            'simwajib' => 0.0,
            'angkop' => 0.0,
            'angla' => 0.0,
            'telpri' => 0.0,
            'pajak' => 0.0,
            'pribadi' => 0.0,
            'lain' => 0.0,
            'ktg' => '-',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}