<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ResumePasienRanapTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('resume_pasien_ranap')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('resume_pasien_ranap')->insert(array (
          0 => 
          array (
            'no_rawat' => '2025/06/18/000001',
            'kd_dokter' => 'D0000004',
            'diagnosa_awal' => '-',
            'alasan' => '',
            'keluhan_utama' => 'WQWQW',
            'pemeriksaan_fisik' => 'WQWQW',
            'jalannya_penyakit' => 'WQWQW',
            'pemeriksaan_penunjang' => 'WQWQW',
            'hasil_laborat' => 'WQWQW',
            'tindakan_dan_operasi' => 'WQW',
            'obat_di_rs' => 'QWQ',
            'diagnosa_utama' => 'TES',
            'kd_diagnosa_utama' => 'E10',
            'diagnosa_sekunder' => '',
            'kd_diagnosa_sekunder' => 'I11.0',
            'diagnosa_sekunder2' => '',
            'kd_diagnosa_sekunder2' => '',
            'diagnosa_sekunder3' => '',
            'kd_diagnosa_sekunder3' => '',
            'diagnosa_sekunder4' => '',
            'kd_diagnosa_sekunder4' => '',
            'prosedur_utama' => '',
            'kd_prosedur_utama' => '',
            'prosedur_sekunder' => '',
            'kd_prosedur_sekunder' => '',
            'prosedur_sekunder2' => '',
            'kd_prosedur_sekunder2' => '',
            'prosedur_sekunder3' => '',
            'kd_prosedur_sekunder3' => '',
            'alergi' => '',
            'diet' => '',
            'lab_belum' => '',
            'edukasi' => '',
            'cara_keluar' => 'Atas Izin Dokter',
            'ket_keluar' => '',
            'keadaan' => 'Membaik',
            'ket_keadaan' => '',
            'dilanjutkan' => 'Kembali Ke RS',
            'ket_dilanjutkan' => '',
            'kontrol' => '2025-06-30 11:54:39',
            'obat_pulang' => '',
          ),
          1 => 
          array (
            'no_rawat' => '2025/06/20/000002',
            'kd_dokter' => 'D0000004',
            'diagnosa_awal' => '-',
            'alasan' => '',
            'keluhan_utama' => '1',
            'pemeriksaan_fisik' => '1',
            'jalannya_penyakit' => '1',
            'pemeriksaan_penunjang' => '1',
            'hasil_laborat' => '1',
            'tindakan_dan_operasi' => '1',
            'obat_di_rs' => '',
            'diagnosa_utama' => '1',
            'kd_diagnosa_utama' => '',
            'diagnosa_sekunder' => '',
            'kd_diagnosa_sekunder' => '',
            'diagnosa_sekunder2' => '',
            'kd_diagnosa_sekunder2' => '',
            'diagnosa_sekunder3' => '',
            'kd_diagnosa_sekunder3' => '',
            'diagnosa_sekunder4' => '',
            'kd_diagnosa_sekunder4' => '',
            'prosedur_utama' => '',
            'kd_prosedur_utama' => '',
            'prosedur_sekunder' => '',
            'kd_prosedur_sekunder' => '',
            'prosedur_sekunder2' => '',
            'kd_prosedur_sekunder2' => '',
            'prosedur_sekunder3' => '',
            'kd_prosedur_sekunder3' => '',
            'alergi' => '',
            'diet' => '',
            'lab_belum' => '',
            'edukasi' => '',
            'cara_keluar' => 'Atas Izin Dokter',
            'ket_keluar' => '',
            'keadaan' => 'Membaik',
            'ket_keadaan' => '',
            'dilanjutkan' => 'Kembali Ke RS',
            'ket_dilanjutkan' => '',
            'kontrol' => '2025-06-27 14:37:44',
            'obat_pulang' => '1',
          ),
          2 => 
          array (
            'no_rawat' => '2025/06/28/000001',
            'kd_dokter' => 'D0000004',
            'diagnosa_awal' => '-',
            'alasan' => '',
            'keluhan_utama' => '1, ',
            'pemeriksaan_fisik' => 'tes',
            'jalannya_penyakit' => 'qwqw',
            'pemeriksaan_penunjang' => 'wqwqw',
            'hasil_laborat' => 'qwqw',
            'tindakan_dan_operasi' => 'wqwqw',
            'obat_di_rs' => 'qwqw',
            'diagnosa_utama' => 'Abdominal pregnancy',
            'kd_diagnosa_utama' => 'O00.0',
            'diagnosa_sekunder' => '',
            'kd_diagnosa_sekunder' => '',
            'diagnosa_sekunder2' => '',
            'kd_diagnosa_sekunder2' => '',
            'diagnosa_sekunder3' => '',
            'kd_diagnosa_sekunder3' => '',
            'diagnosa_sekunder4' => '',
            'kd_diagnosa_sekunder4' => '',
            'prosedur_utama' => '',
            'kd_prosedur_utama' => '',
            'prosedur_sekunder' => '',
            'kd_prosedur_sekunder' => '',
            'prosedur_sekunder2' => '',
            'kd_prosedur_sekunder2' => '',
            'prosedur_sekunder3' => '',
            'kd_prosedur_sekunder3' => '',
            'alergi' => '',
            'diet' => '',
            'lab_belum' => 'qwqw',
            'edukasi' => 'qwqw',
            'cara_keluar' => 'Atas Izin Dokter',
            'ket_keluar' => '',
            'keadaan' => 'Membaik',
            'ket_keadaan' => '',
            'dilanjutkan' => 'Kembali Ke RS',
            'ket_dilanjutkan' => '',
            'kontrol' => '2025-06-28 10:22:37',
            'obat_pulang' => 'wqwqwqw',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}