<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TelaahFarmasiTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('telaah_farmasi')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('telaah_farmasi')->insert([
            0 => [
                'no_resep' => '202504260001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            1 => [
                'no_resep' => '202504270002',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            2 => [
                'no_resep' => '202505260001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '-',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '-',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            3 => [
                'no_resep' => '202506300001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            4 => [
                'no_resep' => '202507050001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            5 => [
                'no_resep' => '202507230002',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            6 => [
                'no_resep' => '202507290001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            7 => [
                'no_resep' => '202508040002',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            8 => [
                'no_resep' => '202508110001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '12/09/1988/001',
            ],
            9 => [
                'no_resep' => '202508190001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            10 => [
                'no_resep' => '202508210001',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
            11 => [
                'no_resep' => '202508250002',
                'resep_identifikasi_pasien' => 'Ya',
                'resep_ket_identifikasi_pasien' => '',
                'resep_tepat_obat' => 'Ya',
                'resep_ket_tepat_obat' => '',
                'resep_tepat_dosis' => 'Ya',
                'resep_ket_tepat_dosis' => '',
                'resep_tepat_cara_pemberian' => 'Ya',
                'resep_ket_tepat_cara_pemberian' => '',
                'resep_tepat_waktu_pemberian' => 'Ya',
                'resep_ket_tepat_waktu_pemberian' => '',
                'resep_ada_tidak_duplikasi_obat' => 'Tidak',
                'resep_ket_ada_tidak_duplikasi_obat' => '',
                'resep_interaksi_obat' => 'Tidak',
                'resep_ket_interaksi_obat' => '',
                'resep_kontra_indikasi_obat' => 'Tidak',
                'resep_ket_kontra_indikasi_obat' => '',
                'obat_tepat_pasien' => 'Ya',
                'obat_tepat_obat' => 'Ya',
                'obat_tepat_dosis' => 'Ya',
                'obat_tepat_cara_pemberian' => 'Ya',
                'obat_tepat_waktu_pemberian' => 'Ya',
                'nip' => '123124',
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
