<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TemporaryBayarRanapTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('temporary_bayar_ranap')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('temporary_bayar_ranap')->insert(array (
          0 => 
          array (
            'no' => 0,
            'temp1' => 'No.Nota',
            'temp2' => ': 2025/08/26/RI0001',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          1 => 
          array (
            'no' => 1,
            'temp1' => 'Bangsal/Kamar',
            'temp2' => ': VUP.01, Kamar Kelas VIP',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          2 => 
          array (
            'no' => 2,
            'temp1' => 'Tgl.Perawatan',
            'temp2' => ': 19 August 2025 09:46:28 s.d. 26 August 2025 00:00:00 ( 0 Hari )',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          3 => 
          array (
            'no' => 3,
            'temp1' => 'No.R.M.',
            'temp2' => ': 000023',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          4 => 
          array (
            'no' => 4,
            'temp1' => 'Nama Pasien',
            'temp2' => ': RAHMA NIA (33Th)',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          5 => 
          array (
            'no' => 5,
            'temp1' => 'Alamat Pasien',
            'temp2' => ': RT 01 RW 02, CISARANTEN ENDAH, ARCAMANIK, KOTA BANDUNG',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          6 => 
          array (
            'no' => 6,
            'temp1' => 'Registrasi',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '10,000',
            'temp8' => 'Registrasi',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          7 => 
          array (
            'no' => 7,
            'temp1' => 'Ruang',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Kamar',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          8 => 
          array (
            'no' => 8,
            'temp1' => '                           ',
            'temp2' => 'VUP.01, Kamar Kelas VIP',
            'temp3' => ':',
            'temp4' => '550,000',
            'temp5' => '0.0',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => 'Kamar',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          9 => 
          array (
            'no' => 9,
            'temp1' => 'Rincian Biaya',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Ranap Dokter',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          10 => 
          array (
            'no' => 10,
            'temp1' => '1. Obat & BHP',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Obat',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          11 => 
          array (
            'no' => 11,
            'temp1' => 'Resep Pulang',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Resep Pulang',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          12 => 
          array (
            'no' => 12,
            'temp1' => '                           ',
            'temp2' => 'Acyclovir 200 mg Tablet 2 x 1',
            'temp3' => ':',
            'temp4' => '1,367',
            'temp5' => '10.0',
            'temp6' => '0',
            'temp7' => '13,670',
            'temp8' => 'Resep Pulang',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          13 => 
          array (
            'no' => 13,
            'temp1' => '                           ',
            'temp2' => 'Alovell 70 mg Tablet 3 x 1',
            'temp3' => ':',
            'temp4' => '134,066',
            'temp5' => '10.0',
            'temp6' => '0',
            'temp7' => '1,340,660',
            'temp8' => 'Resep Pulang',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          14 => 
          array (
            'no' => 14,
            'temp1' => '',
            'temp2' => 'Total Resep Pulang : 1,354,330',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'TtlResep Pulang',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          15 => 
          array (
            'no' => 17,
            'temp1' => 'SERVICE ADMIN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '136,433',
            'temp8' => 'Service',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          16 => 
          array (
            'no' => 19,
            'temp1' => '',
            'temp2' => '',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          17 => 
          array (
            'no' => 20,
            'temp1' => 'TOTAL TAGIHAN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>1,500,763</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          18 => 
          array (
            'no' => 21,
            'temp1' => 'PPN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>0</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          19 => 
          array (
            'no' => 22,
            'temp1' => 'TAGIHAN+PPN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>1,500,763</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          20 => 
          array (
            'no' => 23,
            'temp1' => '',
            'temp2' => '',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          21 => 
          array (
            'no' => 24,
            'temp1' => 'DEPOSIT',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>0</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          22 => 
          array (
            'no' => 25,
            'temp1' => 'BAYAR',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>1,500,763</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          23 => 
          array (
            'no' => 26,
            'temp1' => '-  BANK DKI',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>1,500,763</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          24 => 
          array (
            'no' => 27,
            'temp1' => 'KEMBALI',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '<b>0</b>',
            'temp8' => 'Tagihan',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}