<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TemporaryLabTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('temporary_lab')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('temporary_lab')->insert(array (
          0 => 
          array (
            'no' => 0,
            'temp1' => 'Hematologi Darah Rutin',
            'temp2' => '',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          1 => 
          array (
            'no' => 1,
            'temp1' => '   Hemoglobin',
            'temp2' => '1212',
            'temp3' => 'g/dl',
            'temp4' => '12-16',
            'temp5' => 'H',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          2 => 
          array (
            'no' => 2,
            'temp1' => '   MCH',
            'temp2' => '12',
            'temp3' => 'pg',
            'temp4' => '27.0-31.0',
            'temp5' => 'L',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          3 => 
          array (
            'no' => 3,
            'temp1' => '   Hematokrit',
            'temp2' => '12',
            'temp3' => '%',
            'temp4' => '37.0-43.0',
            'temp5' => 'T',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          4 => 
          array (
            'no' => 4,
            'temp1' => '   MCHC',
            'temp2' => '12',
            'temp3' => '%',
            'temp4' => '32.0-37.0',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          5 => 
          array (
            'no' => 5,
            'temp1' => '   Trombosit',
            'temp2' => '1',
            'temp3' => '/uL',
            'temp4' => '150.000-440.000',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          6 => 
          array (
            'no' => 6,
            'temp1' => '   Rhesus',
            'temp2' => '21',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          7 => 
          array (
            'no' => 7,
            'temp1' => '   MCV',
            'temp2' => '2',
            'temp3' => 'fL',
            'temp4' => '82.0-92.0',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '',
            'temp9' => '',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
            'temp18' => '',
            'temp19' => '',
            'temp20' => '',
            'temp21' => '',
            'temp22' => '',
            'temp23' => '',
            'temp24' => '',
            'temp25' => '',
            'temp26' => '',
            'temp27' => '',
            'temp28' => '',
            'temp29' => '',
            'temp30' => '',
            'temp31' => '',
            'temp32' => '',
            'temp33' => '',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}