<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TemporaryGiziTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('temporary_gizi')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('temporary_gizi')->insert(array (
          0 => 
          array (
            'no' => 470,
            'temp1' => 'bubur',
            'temp2' => '0',
            'temp3' => '0',
            'temp4' => '0',
            'temp5' => '1',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => '0',
            'temp9' => '0',
            'temp10' => '0',
            'temp11' => '0',
            'temp12' => '0',
            'temp13' => '0',
            'temp14' => '0',
            'temp15' => '0',
            'temp16' => '0',
            'temp17' => '0',
            'temp18' => '0',
            'temp19' => '0',
            'temp20' => '0',
            'temp21' => '0',
            'temp22' => '0',
            'temp23' => '0',
            'temp24' => '0',
            'temp25' => '0',
            'temp26' => '0',
            'temp27' => '0',
            'temp28' => '0',
            'temp29' => '0',
            'temp30' => '0',
            'temp31' => '0',
            'temp32' => '0',
            'temp33' => '1',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          1 => 
          array (
            'no' => 471,
            'temp1' => 'DM',
            'temp2' => '0',
            'temp3' => '0',
            'temp4' => '0',
            'temp5' => '0',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => '0',
            'temp9' => '0',
            'temp10' => '0',
            'temp11' => '0',
            'temp12' => '0',
            'temp13' => '0',
            'temp14' => '0',
            'temp15' => '0',
            'temp16' => '0',
            'temp17' => '0',
            'temp18' => '0',
            'temp19' => '0',
            'temp20' => '0',
            'temp21' => '0',
            'temp22' => '0',
            'temp23' => '0',
            'temp24' => '0',
            'temp25' => '0',
            'temp26' => '0',
            'temp27' => '0',
            'temp28' => '0',
            'temp29' => '0',
            'temp30' => '0',
            'temp31' => '0',
            'temp32' => '0',
            'temp33' => '0',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          2 => 
          array (
            'no' => 472,
            'temp1' => 'RG',
            'temp2' => '0',
            'temp3' => '0',
            'temp4' => '0',
            'temp5' => '0',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => '0',
            'temp9' => '0',
            'temp10' => '0',
            'temp11' => '0',
            'temp12' => '0',
            'temp13' => '0',
            'temp14' => '0',
            'temp15' => '0',
            'temp16' => '0',
            'temp17' => '0',
            'temp18' => '0',
            'temp19' => '0',
            'temp20' => '0',
            'temp21' => '0',
            'temp22' => '0',
            'temp23' => '0',
            'temp24' => '0',
            'temp25' => '0',
            'temp26' => '0',
            'temp27' => '0',
            'temp28' => '0',
            'temp29' => '0',
            'temp30' => '0',
            'temp31' => '0',
            'temp32' => '0',
            'temp33' => '0',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          3 => 
          array (
            'no' => 473,
            'temp1' => 'TKTP',
            'temp2' => '0',
            'temp3' => '0',
            'temp4' => '0',
            'temp5' => '1',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => '0',
            'temp9' => '0',
            'temp10' => '0',
            'temp11' => '0',
            'temp12' => '0',
            'temp13' => '0',
            'temp14' => '0',
            'temp15' => '0',
            'temp16' => '0',
            'temp17' => '0',
            'temp18' => '0',
            'temp19' => '0',
            'temp20' => '0',
            'temp21' => '0',
            'temp22' => '0',
            'temp23' => '0',
            'temp24' => '0',
            'temp25' => '0',
            'temp26' => '0',
            'temp27' => '0',
            'temp28' => '0',
            'temp29' => '0',
            'temp30' => '0',
            'temp31' => '0',
            'temp32' => '0',
            'temp33' => '1',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
          4 => 
          array (
            'no' => 474,
            'temp1' => 'Total : ',
            'temp2' => '0',
            'temp3' => '0',
            'temp4' => '0',
            'temp5' => '2',
            'temp6' => '0',
            'temp7' => '0',
            'temp8' => '0',
            'temp9' => '0',
            'temp10' => '0',
            'temp11' => '0',
            'temp12' => '0',
            'temp13' => '0',
            'temp14' => '0',
            'temp15' => '0',
            'temp16' => '0',
            'temp17' => '0',
            'temp18' => '0',
            'temp19' => '0',
            'temp20' => '0',
            'temp21' => '0',
            'temp22' => '0',
            'temp23' => '0',
            'temp24' => '0',
            'temp25' => '0',
            'temp26' => '0',
            'temp27' => '0',
            'temp28' => '0',
            'temp29' => '0',
            'temp30' => '0',
            'temp31' => '0',
            'temp32' => '0',
            'temp33' => '2',
            'temp34' => '',
            'temp35' => '',
            'temp36' => '',
            'temp37' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}