<?php

namespace Database\Seeders\AutoSeeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TemporaryBayarRalanTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('temporary_bayar_ralan')->truncate();
        Schema::enableForeignKeyConstraints();

        Schema::disableForeignKeyConstraints();
        DB::table('temporary_bayar_ralan')->insert(array (
          0 => 
          array (
            'no' => 31,
            'temp1' => 'SISA PIUTANG',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '814,433',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          1 => 
          array (
            'no' => 32,
            'temp1' => '-  PIUTANG BPJS',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '814,433',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          2 => 
          array (
            'no' => 30,
            'temp1' => 'EKSES',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '0',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          3 => 
          array (
            'no' => 29,
            'temp1' => 'TAGIHAN + PPN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '814,433',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          4 => 
          array (
            'no' => 28,
            'temp1' => 'PPN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '0',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          5 => 
          array (
            'no' => 27,
            'temp1' => 'TOTAL TAGIHAN',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '814,433',
            'temp8' => 'Tagihan',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          6 => 
          array (
            'no' => 23,
            'temp1' => '',
            'temp2' => '199,433',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'TtlObat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          7 => 
          array (
            'no' => 22,
            'temp1' => '',
            'temp2' => 'PPN Obat',
            'temp3' => ':',
            'temp4' => '19,764',
            'temp5' => '1',
            'temp6' => '0',
            'temp7' => '19,764',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          8 => 
          array (
            'no' => 21,
            'temp1' => '',
            'temp2' => 'Afamed tab (OBAT ORAL)',
            'temp3' => ':',
            'temp4' => '11,702',
            'temp5' => '6.0',
            'temp6' => '0',
            'temp7' => '70,212',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          9 => 
          array (
            'no' => 20,
            'temp1' => '',
            'temp2' => 'Ibuprofen 400 mg (OBAT ORAL)',
            'temp3' => ':',
            'temp4' => '1,332',
            'temp5' => '10.0',
            'temp6' => '0',
            'temp7' => '13,320',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          10 => 
          array (
            'no' => 19,
            'temp1' => '',
            'temp2' => 'Amoxsan 500 mg  (OBAT ORAL)',
            'temp3' => ':',
            'temp4' => '6,660',
            'temp5' => '6.0',
            'temp6' => '0',
            'temp7' => '39,960',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          11 => 
          array (
            'no' => 18,
            'temp1' => '',
            'temp2' => 'Acetensa tab (OBAT ORAL)',
            'temp3' => ':',
            'temp4' => '160',
            'temp5' => '8.0',
            'temp6' => '0',
            'temp7' => '1,280',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          12 => 
          array (
            'no' => 17,
            'temp1' => '',
            'temp2' => 'Acyclovir 200 mg Tablet (OBAT ORAL)',
            'temp3' => ':',
            'temp4' => '1,367',
            'temp5' => '8.0',
            'temp6' => '0',
            'temp7' => '10,937',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          13 => 
          array (
            'no' => 16,
            'temp1' => '',
            'temp2' => 'Amlodipine 10 mg (OBAT LUAR)',
            'temp3' => ':',
            'temp4' => '3,996',
            'temp5' => '10.0',
            'temp6' => '4,000',
            'temp7' => '43,960',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          14 => 
          array (
            'no' => 11,
            'temp1' => '',
            'temp2' => 'Pemeriksaan Poliklinik Anak',
            'temp3' => ':',
            'temp4' => '130,000',
            'temp5' => '1.0',
            'temp6' => '0',
            'temp7' => '130,000',
            'temp8' => 'Ralan Dokter',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          15 => 
          array (
            'no' => 12,
            'temp1' => '',
            'temp2' => 'Asuhan Keperawatan',
            'temp3' => ':',
            'temp4' => '90,000',
            'temp5' => '1.0',
            'temp6' => '0',
            'temp7' => '90,000',
            'temp8' => 'Ralan Paramedis',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          16 => 
          array (
            'no' => 13,
            'temp1' => '',
            'temp2' => 'Hematologi Darah Rutin',
            'temp3' => ':',
            'temp4' => '85,000',
            'temp5' => '1.0',
            'temp6' => '0',
            'temp7' => '85,000',
            'temp8' => 'Laborat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          17 => 
          array (
            'no' => 14,
            'temp1' => '',
            'temp2' => 'THORAX AP/PA',
            'temp3' => ':',
            'temp4' => '225,000',
            'temp5' => '1.0',
            'temp6' => '0',
            'temp7' => '225,000',
            'temp8' => 'Radiologi',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          18 => 
          array (
            'no' => 15,
            'temp1' => 'Obat & BHP',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Obat',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          19 => 
          array (
            'no' => 9,
            'temp1' => 'Tindakan',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Ralan Dokter',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          20 => 
          array (
            'no' => 10,
            'temp1' => '',
            'temp2' => 'Administrasi  Asuransi / Pihak ke - III',
            'temp3' => ':',
            'temp4' => '75,000',
            'temp5' => '1.0',
            'temp6' => '0',
            'temp7' => '75,000',
            'temp8' => 'Ralan Dokter',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          21 => 
          array (
            'no' => 5,
            'temp1' => 'Alamat Pasien',
            'temp2' => ': TES, KEDUNGWARU, PREMBUN, KABUPATEN KEBUMEN',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          22 => 
          array (
            'no' => 6,
            'temp1' => 'Dokter ',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          23 => 
          array (
            'no' => 7,
            'temp1' => '',
            'temp2' => 'dr. Hilyatul Nadia',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => 'Dokter',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          24 => 
          array (
            'no' => 8,
            'temp1' => 'Registrasi',
            'temp2' => ':',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '10,000',
            'temp8' => 'Registrasi',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          25 => 
          array (
            'no' => 3,
            'temp1' => 'No.RM',
            'temp2' => ': 000022',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          26 => 
          array (
            'no' => 4,
            'temp1' => 'Nama Pasien',
            'temp2' => ': RUDI SANTOSO (68Th)',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          27 => 
          array (
            'no' => 1,
            'temp1' => 'Unit/Instansi',
            'temp2' => ': Poliklinik Penyakit Dalam',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          28 => 
          array (
            'no' => 2,
            'temp1' => 'Tanggal & Jam',
            'temp2' => ': 2025-08-25 14:15:57',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
          29 => 
          array (
            'no' => 0,
            'temp1' => 'No.Nota',
            'temp2' => ': 2025/08/25/RJ0001',
            'temp3' => '',
            'temp4' => '',
            'temp5' => '',
            'temp6' => '',
            'temp7' => '',
            'temp8' => '-',
            'temp9' => 'Admin Utama',
            'temp10' => '',
            'temp11' => '',
            'temp12' => '',
            'temp13' => '',
            'temp14' => '',
            'temp15' => '',
            'temp16' => '',
            'temp17' => '',
          ),
        ));
        Schema::enableForeignKeyConstraints();
    }
}